// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if JobService
  import Foundation
  import GoogleCloudWkt

  /// Parameters that configure the active learning pipeline. Active learning will
  ///  label the data incrementally by several iterations. For every iteration, it
  ///  will select a batch of data based on the sampling strategy.
  public struct ActiveLearningConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Active learning data sampling config. For every active learning labeling
    /// iteration, it will select a batch of data based on the sampling strategy.
    public var sampleConfig: SampleConfig? = nil

    /// CMLE training config. For every active learning labeling iteration, system
    /// will train a machine learning model on CMLE. The trained model will be used
    /// by data sampling algorithm to select DataItems.
    public var trainingConfig: TrainingConfig? = nil

    /// Required. Max human labeling DataItems. The rest part will be labeled by
    /// machine.
    public var humanLabelingBudget: OneOf_HumanLabelingBudget? = nil

    /// Initialize a new instance of `ActiveLearningConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ActiveLearningConfig().with { $0.maxDataItemCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case maxDataItemCount = "maxDataItemCount"
      case maxDataItemPercentage = "maxDataItemPercentage"
      case sampleConfig = "sampleConfig"
      case trainingConfig = "trainingConfig"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.sampleConfig = try container.decodeIfPresent(SampleConfig.self, forKey: .sampleConfig)
      self.trainingConfig = try container.decodeIfPresent(
        TrainingConfig.self, forKey: .trainingConfig)

      var humanLabelingBudget: OneOf_HumanLabelingBudget? = nil
      let humanLabelingBudgetCheckAndSet = {
        if humanLabelingBudget != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'humanLabelingBudget'"))
        }
        humanLabelingBudget = $0
      }
      if let maxDataItemCount = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .maxDataItemCount)
      {
        try humanLabelingBudgetCheckAndSet(.maxDataItemCount(maxDataItemCount))
      }
      if let maxDataItemPercentage = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .maxDataItemPercentage)
      {
        try humanLabelingBudgetCheckAndSet(.maxDataItemPercentage(maxDataItemPercentage))
      }
      self.humanLabelingBudget = humanLabelingBudget
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sampleConfig, forKey: .sampleConfig)
      try container.encode(self.trainingConfig, forKey: .trainingConfig)

      if let choice = self.humanLabelingBudget {
        switch choice {
        case .maxDataItemCount(let value):
          try container.encode(value, forKey: .maxDataItemCount)
        case .maxDataItemPercentage(let value):
          try container.encode(value, forKey: .maxDataItemPercentage)
        }
      }
    }

    /// Required. Max human labeling DataItems. The rest part will be labeled by
    /// machine.
    public enum OneOf_HumanLabelingBudget: Codable, Equatable, Sendable {
      /// Max number of human labeled DataItems.
      case maxDataItemCount(Swift.Int64)
      /// Max percent of total DataItems for human labeling.
      case maxDataItemPercentage(Swift.Int32)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ActiveLearningConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
