// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if MigrationService
  import Foundation
  import GoogleCloudWkt
  import GoogleRpc

  /// Runtime operation information for
  /// [MigrationService.BatchMigrateResources][google.cloud.aiplatform.v1.MigrationService.BatchMigrateResources].
  ///
  /// [google.cloud.aiplatform.v1.MigrationService.BatchMigrateResources]: <doc:MigrationService/batchMigrateResources(request:)>
  public struct BatchMigrateResourcesOperationMetadata: Codable, Equatable, GoogleCloudWkt
      ._AnyPackable,
    Sendable
  {
    /// The common part of the operation metadata.
    public var genericMetadata: GenericOperationMetadata? = nil

    /// Partial results that reflect the latest migration operation progress.
    public var partialResults: [BatchMigrateResourcesOperationMetadata.PartialResult] = []

    /// Initialize a new instance of `BatchMigrateResourcesOperationMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BatchMigrateResourcesOperationMetadata().with { $0.genericMetadata = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Represents a partial result in batch migration operation for one
    /// [MigrateResourceRequest][google.cloud.aiplatform.v1.MigrateResourceRequest].
    ///
    /// [google.cloud.aiplatform.v1.MigrateResourceRequest]: <doc:MigrateResourceRequest>
    public struct PartialResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// It's the same as the value in
      /// [BatchMigrateResourcesRequest.migrate_resource_requests][google.cloud.aiplatform.v1.BatchMigrateResourcesRequest.migrate_resource_requests].
      ///
      /// [google.cloud.aiplatform.v1.BatchMigrateResourcesRequest.migrate_resource_requests]: <doc:BatchMigrateResourcesRequest/migrateResourceRequests>
      public var request: MigrateResourceRequest? = nil

      /// If the resource's migration is ongoing, none of the result will be set.
      /// If the resource's migration is finished, either error or one of the
      /// migrated resource name will be filled.
      public var result: OneOf_Result? = nil

      /// Initialize a new instance of `PartialResult`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = PartialResult().with { $0.error = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: String, CodingKey {
        case error = "error"
        case model = "model"
        case dataset = "dataset"
        case request = "request"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.request = try container.decodeIfPresent(MigrateResourceRequest.self, forKey: .request)

        var result: OneOf_Result? = nil
        let resultCheckAndSet = {
          if result != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'result'"))
          }
          result = $0
        }
        if let error = try container.decodeIfPresent(GoogleRpc.Status?.self, forKey: .error) {
          try resultCheckAndSet(.error(error))
        }
        if let model = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
          try resultCheckAndSet(.model(model))
        }
        if let dataset = try container.decodeIfPresent(Swift.String.self, forKey: .dataset) {
          try resultCheckAndSet(.dataset(dataset))
        }
        self.result = result
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.request, forKey: .request)

        if let choice = self.result {
          switch choice {
          case .error(let value):
            try container.encode(value, forKey: .error)
          case .model(let value):
            try container.encode(value, forKey: .model)
          case .dataset(let value):
            try container.encode(value, forKey: .dataset)
          }
        }
      }

      /// If the resource's migration is ongoing, none of the result will be set.
      /// If the resource's migration is finished, either error or one of the
      /// migrated resource name will be filled.
      public enum OneOf_Result: Codable, Equatable, Sendable {
        /// The error result of the migration request in case of failure.
        indirect case error(GoogleRpc.Status?)
        /// Migrated model resource name.
        case model(Swift.String)
        /// Migrated dataset resource name.
        case dataset(Swift.String)
      }

      public static var _anyTypeUrl: String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.BatchMigrateResourcesOperationMetadata.PartialResult"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.BatchMigrateResourcesOperationMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
