// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PredictionService
  import Foundation
  import GoogleCloudWkt

  /// A response candidate generated from the model.
  public struct Candidate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Index of the candidate.
    public var index: Swift.Int32 = Swift.Int32()

    /// Output only. Content parts of the candidate.
    public var content: Content? = nil

    /// Output only. Confidence score of the candidate.
    public var score: Swift.Double = Swift.Double()

    /// Output only. Average log probability score of the candidate.
    public var avgLogprobs: Swift.Double = Swift.Double()

    /// Output only. Log-likelihood scores for the response tokens and top tokens
    public var logprobsResult: LogprobsResult? = nil

    /// Output only. The reason why the model stopped generating tokens.
    /// If empty, the model has not stopped generating the tokens.
    public var finishReason: Candidate.FinishReason = Candidate.FinishReason()

    /// Output only. List of ratings for the safety of a response candidate.
    ///
    /// There is at most one rating per category.
    public var safetyRatings: [SafetyRating] = []

    /// Output only. Describes the reason the mode stopped generating tokens in
    /// more detail. This is only filled when `finish_reason` is set.
    public var finishMessage: Swift.String? = nil

    /// Output only. Source attribution of the generated content.
    public var citationMetadata: CitationMetadata? = nil

    /// Output only. Metadata specifies sources used to ground generated content.
    public var groundingMetadata: GroundingMetadata? = nil

    /// Output only. Metadata related to url context retrieval tool.
    public var urlContextMetadata: UrlContextMetadata? = nil

    /// Initialize a new instance of `Candidate`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Candidate().with { $0.index = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The reason why the model stopped generating tokens.
    /// If empty, the model has not stopped generating the tokens.
    public enum FinishReason: Codable, Equatable, Sendable {
      /// The finish reason is unspecified.
      case unspecified
      /// Token generation reached a natural stopping point or a configured stop
      /// sequence.
      case stop
      /// Token generation reached the configured maximum output tokens.
      case maxTokens
      /// Token generation stopped because the content potentially contains safety
      /// violations. NOTE: When streaming,
      /// [content][google.cloud.aiplatform.v1.Candidate.content] is empty if
      /// content filters blocks the output.
      ///
      /// [google.cloud.aiplatform.v1.Candidate.content]: <doc:Candidate/content>
      case safety
      /// Token generation stopped because the content potentially contains
      /// copyright violations.
      case recitation
      /// All other reasons that stopped the token generation.
      case other
      /// Token generation stopped because the content contains forbidden terms.
      case blocklist
      /// Token generation stopped for potentially containing prohibited content.
      case prohibitedContent
      /// Token generation stopped because the content potentially contains
      /// Sensitive Personally Identifiable Information (SPII).
      case spii
      /// The function call generated by the model is invalid.
      case malformedFunctionCall
      /// The model response was blocked by Model Armor.
      case modelArmor
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .stop: return 1
        case .maxTokens: return 2
        case .safety: return 3
        case .recitation: return 4
        case .other: return 5
        case .blocklist: return 6
        case .prohibitedContent: return 7
        case .spii: return 8
        case .malformedFunctionCall: return 9
        case .modelArmor: return 10
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "FINISH_REASON_UNSPECIFIED"
        case .stop: return "STOP"
        case .maxTokens: return "MAX_TOKENS"
        case .safety: return "SAFETY"
        case .recitation: return "RECITATION"
        case .other: return "OTHER"
        case .blocklist: return "BLOCKLIST"
        case .prohibitedContent: return "PROHIBITED_CONTENT"
        case .spii: return "SPII"
        case .malformedFunctionCall: return "MALFORMED_FUNCTION_CALL"
        case .modelArmor: return "MODEL_ARMOR"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "FINISH_REASON_UNSPECIFIED": self = .unspecified
        case "STOP": self = .stop
        case "MAX_TOKENS": self = .maxTokens
        case "SAFETY": self = .safety
        case "RECITATION": self = .recitation
        case "OTHER": self = .other
        case "BLOCKLIST": self = .blocklist
        case "PROHIBITED_CONTENT": self = .prohibitedContent
        case "SPII": self = .spii
        case "MALFORMED_FUNCTION_CALL": self = .malformedFunctionCall
        case "MODEL_ARMOR": self = .modelArmor
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .stop
        case 2: self = .maxTokens
        case 3: self = .safety
        case 4: self = .recitation
        case 5: self = .other
        case 6: self = .blocklist
        case 7: self = .prohibitedContent
        case 8: self = .spii
        case 9: self = .malformedFunctionCall
        case 10: self = .modelArmor
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .stop: return try container.encode(1)
        case .maxTokens: return try container.encode(2)
        case .safety: return try container.encode(3)
        case .recitation: return try container.encode(4)
        case .other: return try container.encode(5)
        case .blocklist: return try container.encode(6)
        case .prohibitedContent: return try container.encode(7)
        case .spii: return try container.encode(8)
        case .malformedFunctionCall: return try container.encode(9)
        case .modelArmor: return try container.encode(10)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.Candidate"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
