// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if EvaluationService || GenAiTuningService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Spec for custom output.
  public struct CustomOutput: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Custom output.
    public var customOutput: OneOf_CustomOutput? = nil

    /// Initialize a new instance of `CustomOutput`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomOutput().with { $0.rawOutputs = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case rawOutputs = "rawOutputs"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var customOutput: OneOf_CustomOutput? = nil
      let customOutputCheckAndSet = {
        if customOutput != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'customOutput'"))
        }
        customOutput = $0
      }
      if let rawOutputs = try container.decodeIfPresent(RawOutput?.self, forKey: .rawOutputs) {
        try customOutputCheckAndSet(.rawOutputs(rawOutputs))
      }
      self.customOutput = customOutput
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.customOutput {
        switch choice {
        case .rawOutputs(let value):
          try container.encode(value, forKey: .rawOutputs)
        }
      }
    }

    /// Custom output.
    public enum OneOf_CustomOutput: Codable, Equatable, Sendable {
      /// Output only. List of raw output strings.
      indirect case rawOutputs(RawOutput?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.CustomOutput"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
