// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FeaturestoreService
  import Foundation
  import GoogleCloudWkt
  import GoogleType

  /// Request message for
  /// [FeaturestoreService.DeleteFeatureValues][google.cloud.aiplatform.v1.FeaturestoreService.DeleteFeatureValues].
  ///
  /// [google.cloud.aiplatform.v1.FeaturestoreService.DeleteFeatureValues]: <doc:FeaturestoreService/deleteFeatureValues(request:)>
  public struct DeleteFeatureValuesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the EntityType grouping the Features for
    /// which values are being deleted from. Format:
    /// `projects/{project}/locations/{location}/featurestores/{featurestore}/entityTypes/{entityType}`
    public var entityType: Swift.String = Swift.String()

    /// Defines options to select feature values to be deleted.
    public var deleteOption: OneOf_DeleteOption? = nil

    /// Initialize a new instance of `DeleteFeatureValuesRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeleteFeatureValuesRequest().with { $0.selectEntity = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case selectEntity = "selectEntity"
      case selectTimeRangeAndFeature = "selectTimeRangeAndFeature"
      case entityType = "entityType"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.entityType = try container.decode(Swift.String.self, forKey: .entityType)

      var deleteOption: OneOf_DeleteOption? = nil
      let deleteOptionCheckAndSet = {
        if deleteOption != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'deleteOption'"))
        }
        deleteOption = $0
      }
      if let selectEntity = try container.decodeIfPresent(
        DeleteFeatureValuesRequest.SelectEntity?.self, forKey: .selectEntity)
      {
        try deleteOptionCheckAndSet(.selectEntity(selectEntity))
      }
      if let selectTimeRangeAndFeature = try container.decodeIfPresent(
        DeleteFeatureValuesRequest.SelectTimeRangeAndFeature?.self,
        forKey: .selectTimeRangeAndFeature)
      {
        try deleteOptionCheckAndSet(.selectTimeRangeAndFeature(selectTimeRangeAndFeature))
      }
      self.deleteOption = deleteOption
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.entityType, forKey: .entityType)

      if let choice = self.deleteOption {
        switch choice {
        case .selectEntity(let value):
          try container.encode(value, forKey: .selectEntity)
        case .selectTimeRangeAndFeature(let value):
          try container.encode(value, forKey: .selectTimeRangeAndFeature)
        }
      }
    }

    /// Message to select entity.
    /// If an entity id is selected, all the feature values corresponding to the
    /// entity id will be deleted, including the entityId.
    public struct SelectEntity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Selectors choosing feature values of which entity id to be
      /// deleted from the EntityType.
      public var entityIdSelector: EntityIdSelector? = nil

      /// Initialize a new instance of `SelectEntity`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SelectEntity().with { $0.entityIdSelector = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.DeleteFeatureValuesRequest.SelectEntity"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Message to select time range and feature.
    /// Values of the selected feature generated within an inclusive time range
    /// will be deleted. Using this option permanently deletes the feature values
    /// from the specified feature IDs within the specified time range.
    /// This might include data from the online storage. If you want to retain
    /// any deleted historical data in the online storage, you must re-ingest it.
    public struct SelectTimeRangeAndFeature: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Select feature generated within a half-inclusive time range.
      /// The time range is lower inclusive and upper exclusive.
      public var timeRange: GoogleType.Interval? = nil

      /// Required. Selectors choosing which feature values to be deleted from the
      /// EntityType.
      public var featureSelector: FeatureSelector? = nil

      /// If set, data will not be deleted from online storage.
      /// When time range is older than the data in online storage, setting this to
      /// be true will make the deletion have no impact on online serving.
      public var skipOnlineStorageDelete: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `SelectTimeRangeAndFeature`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SelectTimeRangeAndFeature().with { $0.timeRange = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.DeleteFeatureValuesRequest.SelectTimeRangeAndFeature"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Defines options to select feature values to be deleted.
    public enum OneOf_DeleteOption: Codable, Equatable, Sendable {
      /// Select feature values to be deleted by specifying entities.
      indirect case selectEntity(DeleteFeatureValuesRequest.SelectEntity?)
      /// Select feature values to be deleted by specifying time range and
      /// features.
      indirect case selectTimeRangeAndFeature(DeleteFeatureValuesRequest.SelectTimeRangeAndFeature?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.DeleteFeatureValuesRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
