// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FeaturestoreService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Selector for entityId. Getting ids from the given source.
  public struct EntityIdSelector: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Source column that holds entity IDs. If not provided, entity IDs are
    /// extracted from the column named entity_id.
    public var entityIdField: Swift.String = Swift.String()

    /// Details about the source data, including the location of the storage and
    /// the format.
    public var entityIdsSource: OneOf_EntityIdsSource? = nil

    /// Initialize a new instance of `EntityIdSelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EntityIdSelector().with { $0.csvSource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case csvSource = "csvSource"
      case entityIdField = "entityIdField"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.entityIdField = try container.decode(Swift.String.self, forKey: .entityIdField)

      var entityIdsSource: OneOf_EntityIdsSource? = nil
      let entityIdsSourceCheckAndSet = {
        if entityIdsSource != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'entityIdsSource'"))
        }
        entityIdsSource = $0
      }
      if let csvSource = try container.decodeIfPresent(CsvSource?.self, forKey: .csvSource) {
        try entityIdsSourceCheckAndSet(.csvSource(csvSource))
      }
      self.entityIdsSource = entityIdsSource
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.entityIdField, forKey: .entityIdField)

      if let choice = self.entityIdsSource {
        switch choice {
        case .csvSource(let value):
          try container.encode(value, forKey: .csvSource)
        }
      }
    }

    /// Details about the source data, including the location of the storage and
    /// the format.
    public enum OneOf_EntityIdsSource: Codable, Equatable, Sendable {
      /// Source of Csv
      indirect case csvSource(CsvSource?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.EntityIdSelector"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
