// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GenAiTuningService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt
  import GoogleRpc

  /// Evaluate Dataset Run Result for Tuning Job.
  public struct EvaluateDatasetRun: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Deprecated: The updated architecture uses evaluation_run
    /// instead.
    @available(*, deprecated)
    public var operationName: Swift.String = Swift.String()

    /// Output only. The resource name of the evaluation run. Format:
    /// `projects/{project}/locations/{location}/evaluationRuns/{evaluation_run_id}`.
    public var evaluationRun: Swift.String = Swift.String()

    /// Output only. The checkpoint id used in the evaluation run. Only populated
    /// when evaluating checkpoints.
    public var checkpointId: Swift.String = Swift.String()

    /// Output only. Results for EvaluationService.
    public var evaluateDatasetResponse: EvaluateDatasetResponse? = nil

    /// Output only. The error of the evaluation run if any.
    public var error: GoogleRpc.Status? = nil

    /// Initialize a new instance of `EvaluateDatasetRun`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EvaluateDatasetRun().with { $0.operationName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.EvaluateDatasetRun"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
