// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if EvaluationService
  import Foundation
  import GoogleCloudWkt

  /// Request message for EvaluationService.EvaluateInstances.
  public struct EvaluateInstancesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the Location to evaluate the instances.
    /// Format: `projects/{project}/locations/{location}`
    public var location: Swift.String = Swift.String()

    /// Instances and specs for evaluation
    public var metricInputs: OneOf_MetricInputs? = nil

    /// Initialize a new instance of `EvaluateInstancesRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EvaluateInstancesRequest().with { $0.exactMatchInput = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case exactMatchInput = "exactMatchInput"
      case bleuInput = "bleuInput"
      case rougeInput = "rougeInput"
      case fluencyInput = "fluencyInput"
      case coherenceInput = "coherenceInput"
      case safetyInput = "safetyInput"
      case groundednessInput = "groundednessInput"
      case fulfillmentInput = "fulfillmentInput"
      case summarizationQualityInput = "summarizationQualityInput"
      case pairwiseSummarizationQualityInput = "pairwiseSummarizationQualityInput"
      case summarizationHelpfulnessInput = "summarizationHelpfulnessInput"
      case summarizationVerbosityInput = "summarizationVerbosityInput"
      case questionAnsweringQualityInput = "questionAnsweringQualityInput"
      case pairwiseQuestionAnsweringQualityInput = "pairwiseQuestionAnsweringQualityInput"
      case questionAnsweringRelevanceInput = "questionAnsweringRelevanceInput"
      case questionAnsweringHelpfulnessInput = "questionAnsweringHelpfulnessInput"
      case questionAnsweringCorrectnessInput = "questionAnsweringCorrectnessInput"
      case pointwiseMetricInput = "pointwiseMetricInput"
      case pairwiseMetricInput = "pairwiseMetricInput"
      case toolCallValidInput = "toolCallValidInput"
      case toolNameMatchInput = "toolNameMatchInput"
      case toolParameterKeyMatchInput = "toolParameterKeyMatchInput"
      case toolParameterKvMatchInput = "toolParameterKvMatchInput"
      case cometInput = "cometInput"
      case metricxInput = "metricxInput"
      case location = "location"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.location = try container.decode(Swift.String.self, forKey: .location)

      var metricInputs: OneOf_MetricInputs? = nil
      let metricInputsCheckAndSet = {
        if metricInputs != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'metricInputs'"))
        }
        metricInputs = $0
      }
      if let exactMatchInput = try container.decodeIfPresent(
        ExactMatchInput?.self, forKey: .exactMatchInput)
      {
        try metricInputsCheckAndSet(.exactMatchInput(exactMatchInput))
      }
      if let bleuInput = try container.decodeIfPresent(BleuInput?.self, forKey: .bleuInput) {
        try metricInputsCheckAndSet(.bleuInput(bleuInput))
      }
      if let rougeInput = try container.decodeIfPresent(RougeInput?.self, forKey: .rougeInput) {
        try metricInputsCheckAndSet(.rougeInput(rougeInput))
      }
      if let fluencyInput = try container.decodeIfPresent(FluencyInput?.self, forKey: .fluencyInput)
      {
        try metricInputsCheckAndSet(.fluencyInput(fluencyInput))
      }
      if let coherenceInput = try container.decodeIfPresent(
        CoherenceInput?.self, forKey: .coherenceInput)
      {
        try metricInputsCheckAndSet(.coherenceInput(coherenceInput))
      }
      if let safetyInput = try container.decodeIfPresent(SafetyInput?.self, forKey: .safetyInput) {
        try metricInputsCheckAndSet(.safetyInput(safetyInput))
      }
      if let groundednessInput = try container.decodeIfPresent(
        GroundednessInput?.self, forKey: .groundednessInput)
      {
        try metricInputsCheckAndSet(.groundednessInput(groundednessInput))
      }
      if let fulfillmentInput = try container.decodeIfPresent(
        FulfillmentInput?.self, forKey: .fulfillmentInput)
      {
        try metricInputsCheckAndSet(.fulfillmentInput(fulfillmentInput))
      }
      if let summarizationQualityInput = try container.decodeIfPresent(
        SummarizationQualityInput?.self, forKey: .summarizationQualityInput)
      {
        try metricInputsCheckAndSet(.summarizationQualityInput(summarizationQualityInput))
      }
      if let pairwiseSummarizationQualityInput = try container.decodeIfPresent(
        PairwiseSummarizationQualityInput?.self, forKey: .pairwiseSummarizationQualityInput)
      {
        try metricInputsCheckAndSet(
          .pairwiseSummarizationQualityInput(pairwiseSummarizationQualityInput))
      }
      if let summarizationHelpfulnessInput = try container.decodeIfPresent(
        SummarizationHelpfulnessInput?.self, forKey: .summarizationHelpfulnessInput)
      {
        try metricInputsCheckAndSet(.summarizationHelpfulnessInput(summarizationHelpfulnessInput))
      }
      if let summarizationVerbosityInput = try container.decodeIfPresent(
        SummarizationVerbosityInput?.self, forKey: .summarizationVerbosityInput)
      {
        try metricInputsCheckAndSet(.summarizationVerbosityInput(summarizationVerbosityInput))
      }
      if let questionAnsweringQualityInput = try container.decodeIfPresent(
        QuestionAnsweringQualityInput?.self, forKey: .questionAnsweringQualityInput)
      {
        try metricInputsCheckAndSet(.questionAnsweringQualityInput(questionAnsweringQualityInput))
      }
      if let pairwiseQuestionAnsweringQualityInput = try container.decodeIfPresent(
        PairwiseQuestionAnsweringQualityInput?.self, forKey: .pairwiseQuestionAnsweringQualityInput)
      {
        try metricInputsCheckAndSet(
          .pairwiseQuestionAnsweringQualityInput(pairwiseQuestionAnsweringQualityInput))
      }
      if let questionAnsweringRelevanceInput = try container.decodeIfPresent(
        QuestionAnsweringRelevanceInput?.self, forKey: .questionAnsweringRelevanceInput)
      {
        try metricInputsCheckAndSet(
          .questionAnsweringRelevanceInput(questionAnsweringRelevanceInput))
      }
      if let questionAnsweringHelpfulnessInput = try container.decodeIfPresent(
        QuestionAnsweringHelpfulnessInput?.self, forKey: .questionAnsweringHelpfulnessInput)
      {
        try metricInputsCheckAndSet(
          .questionAnsweringHelpfulnessInput(questionAnsweringHelpfulnessInput))
      }
      if let questionAnsweringCorrectnessInput = try container.decodeIfPresent(
        QuestionAnsweringCorrectnessInput?.self, forKey: .questionAnsweringCorrectnessInput)
      {
        try metricInputsCheckAndSet(
          .questionAnsweringCorrectnessInput(questionAnsweringCorrectnessInput))
      }
      if let pointwiseMetricInput = try container.decodeIfPresent(
        PointwiseMetricInput?.self, forKey: .pointwiseMetricInput)
      {
        try metricInputsCheckAndSet(.pointwiseMetricInput(pointwiseMetricInput))
      }
      if let pairwiseMetricInput = try container.decodeIfPresent(
        PairwiseMetricInput?.self, forKey: .pairwiseMetricInput)
      {
        try metricInputsCheckAndSet(.pairwiseMetricInput(pairwiseMetricInput))
      }
      if let toolCallValidInput = try container.decodeIfPresent(
        ToolCallValidInput?.self, forKey: .toolCallValidInput)
      {
        try metricInputsCheckAndSet(.toolCallValidInput(toolCallValidInput))
      }
      if let toolNameMatchInput = try container.decodeIfPresent(
        ToolNameMatchInput?.self, forKey: .toolNameMatchInput)
      {
        try metricInputsCheckAndSet(.toolNameMatchInput(toolNameMatchInput))
      }
      if let toolParameterKeyMatchInput = try container.decodeIfPresent(
        ToolParameterKeyMatchInput?.self, forKey: .toolParameterKeyMatchInput)
      {
        try metricInputsCheckAndSet(.toolParameterKeyMatchInput(toolParameterKeyMatchInput))
      }
      if let toolParameterKvMatchInput = try container.decodeIfPresent(
        ToolParameterKVMatchInput?.self, forKey: .toolParameterKvMatchInput)
      {
        try metricInputsCheckAndSet(.toolParameterKvMatchInput(toolParameterKvMatchInput))
      }
      if let cometInput = try container.decodeIfPresent(CometInput?.self, forKey: .cometInput) {
        try metricInputsCheckAndSet(.cometInput(cometInput))
      }
      if let metricxInput = try container.decodeIfPresent(MetricxInput?.self, forKey: .metricxInput)
      {
        try metricInputsCheckAndSet(.metricxInput(metricxInput))
      }
      self.metricInputs = metricInputs
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.location, forKey: .location)

      if let choice = self.metricInputs {
        switch choice {
        case .exactMatchInput(let value):
          try container.encode(value, forKey: .exactMatchInput)
        case .bleuInput(let value):
          try container.encode(value, forKey: .bleuInput)
        case .rougeInput(let value):
          try container.encode(value, forKey: .rougeInput)
        case .fluencyInput(let value):
          try container.encode(value, forKey: .fluencyInput)
        case .coherenceInput(let value):
          try container.encode(value, forKey: .coherenceInput)
        case .safetyInput(let value):
          try container.encode(value, forKey: .safetyInput)
        case .groundednessInput(let value):
          try container.encode(value, forKey: .groundednessInput)
        case .fulfillmentInput(let value):
          try container.encode(value, forKey: .fulfillmentInput)
        case .summarizationQualityInput(let value):
          try container.encode(value, forKey: .summarizationQualityInput)
        case .pairwiseSummarizationQualityInput(let value):
          try container.encode(value, forKey: .pairwiseSummarizationQualityInput)
        case .summarizationHelpfulnessInput(let value):
          try container.encode(value, forKey: .summarizationHelpfulnessInput)
        case .summarizationVerbosityInput(let value):
          try container.encode(value, forKey: .summarizationVerbosityInput)
        case .questionAnsweringQualityInput(let value):
          try container.encode(value, forKey: .questionAnsweringQualityInput)
        case .pairwiseQuestionAnsweringQualityInput(let value):
          try container.encode(value, forKey: .pairwiseQuestionAnsweringQualityInput)
        case .questionAnsweringRelevanceInput(let value):
          try container.encode(value, forKey: .questionAnsweringRelevanceInput)
        case .questionAnsweringHelpfulnessInput(let value):
          try container.encode(value, forKey: .questionAnsweringHelpfulnessInput)
        case .questionAnsweringCorrectnessInput(let value):
          try container.encode(value, forKey: .questionAnsweringCorrectnessInput)
        case .pointwiseMetricInput(let value):
          try container.encode(value, forKey: .pointwiseMetricInput)
        case .pairwiseMetricInput(let value):
          try container.encode(value, forKey: .pairwiseMetricInput)
        case .toolCallValidInput(let value):
          try container.encode(value, forKey: .toolCallValidInput)
        case .toolNameMatchInput(let value):
          try container.encode(value, forKey: .toolNameMatchInput)
        case .toolParameterKeyMatchInput(let value):
          try container.encode(value, forKey: .toolParameterKeyMatchInput)
        case .toolParameterKvMatchInput(let value):
          try container.encode(value, forKey: .toolParameterKvMatchInput)
        case .cometInput(let value):
          try container.encode(value, forKey: .cometInput)
        case .metricxInput(let value):
          try container.encode(value, forKey: .metricxInput)
        }
      }
    }

    /// Instances and specs for evaluation
    public enum OneOf_MetricInputs: Codable, Equatable, Sendable {
      /// Auto metric instances.
      /// Instances and metric spec for exact match metric.
      indirect case exactMatchInput(ExactMatchInput?)
      /// Instances and metric spec for bleu metric.
      indirect case bleuInput(BleuInput?)
      /// Instances and metric spec for rouge metric.
      indirect case rougeInput(RougeInput?)
      /// LLM-based metric instance.
      /// General text generation metrics, applicable to other categories.
      /// Input for fluency metric.
      indirect case fluencyInput(FluencyInput?)
      /// Input for coherence metric.
      indirect case coherenceInput(CoherenceInput?)
      /// Input for safety metric.
      indirect case safetyInput(SafetyInput?)
      /// Input for groundedness metric.
      indirect case groundednessInput(GroundednessInput?)
      /// Input for fulfillment metric.
      indirect case fulfillmentInput(FulfillmentInput?)
      /// Input for summarization quality metric.
      indirect case summarizationQualityInput(SummarizationQualityInput?)
      /// Input for pairwise summarization quality metric.
      indirect case pairwiseSummarizationQualityInput(PairwiseSummarizationQualityInput?)
      /// Input for summarization helpfulness metric.
      indirect case summarizationHelpfulnessInput(SummarizationHelpfulnessInput?)
      /// Input for summarization verbosity metric.
      indirect case summarizationVerbosityInput(SummarizationVerbosityInput?)
      /// Input for question answering quality metric.
      indirect case questionAnsweringQualityInput(QuestionAnsweringQualityInput?)
      /// Input for pairwise question answering quality metric.
      indirect case pairwiseQuestionAnsweringQualityInput(PairwiseQuestionAnsweringQualityInput?)
      /// Input for question answering relevance metric.
      indirect case questionAnsweringRelevanceInput(QuestionAnsweringRelevanceInput?)
      /// Input for question answering helpfulness
      /// metric.
      indirect case questionAnsweringHelpfulnessInput(QuestionAnsweringHelpfulnessInput?)
      /// Input for question answering correctness
      /// metric.
      indirect case questionAnsweringCorrectnessInput(QuestionAnsweringCorrectnessInput?)
      /// Input for pointwise metric.
      indirect case pointwiseMetricInput(PointwiseMetricInput?)
      /// Input for pairwise metric.
      indirect case pairwiseMetricInput(PairwiseMetricInput?)
      /// Tool call metric instances.
      /// Input for tool call valid metric.
      indirect case toolCallValidInput(ToolCallValidInput?)
      /// Input for tool name match metric.
      indirect case toolNameMatchInput(ToolNameMatchInput?)
      /// Input for tool parameter key match metric.
      indirect case toolParameterKeyMatchInput(ToolParameterKeyMatchInput?)
      /// Input for tool parameter key value match metric.
      indirect case toolParameterKvMatchInput(ToolParameterKVMatchInput?)
      /// Translation metrics.
      /// Input for Comet metric.
      indirect case cometInput(CometInput?)
      /// Input for Metricx metric.
      indirect case metricxInput(MetricxInput?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.EvaluateInstancesRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
