// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PipelineService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Assigns input data to training, validation, and test sets based on the given
  /// filters, data pieces not matched by any filter are ignored. Currently only
  /// supported for Datasets containing DataItems.
  /// If any of the filters in this message are to match nothing, then they can be
  /// set as '-' (the minus sign).
  ///
  /// Supported only for unstructured Datasets.
  ///
  public struct FilterSplit: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. A filter on DataItems of the Dataset. DataItems that match
    /// this filter are used to train the Model. A filter with same syntax
    /// as the one used in
    /// [DatasetService.ListDataItems][google.cloud.aiplatform.v1.DatasetService.ListDataItems]
    /// may be used. If a single DataItem is matched by more than one of the
    /// FilterSplit filters, then it is assigned to the first set that applies to
    /// it in the training, validation, test order.
    ///
    /// [google.cloud.aiplatform.v1.DatasetService.ListDataItems]: <doc:DatasetServiceClient/listDataItems(request:options:)>
    public var trainingFilter: Swift.String = Swift.String()

    /// Required. A filter on DataItems of the Dataset. DataItems that match
    /// this filter are used to validate the Model. A filter with same syntax
    /// as the one used in
    /// [DatasetService.ListDataItems][google.cloud.aiplatform.v1.DatasetService.ListDataItems]
    /// may be used. If a single DataItem is matched by more than one of the
    /// FilterSplit filters, then it is assigned to the first set that applies to
    /// it in the training, validation, test order.
    ///
    /// [google.cloud.aiplatform.v1.DatasetService.ListDataItems]: <doc:DatasetServiceClient/listDataItems(request:options:)>
    public var validationFilter: Swift.String = Swift.String()

    /// Required. A filter on DataItems of the Dataset. DataItems that match
    /// this filter are used to test the Model. A filter with same syntax
    /// as the one used in
    /// [DatasetService.ListDataItems][google.cloud.aiplatform.v1.DatasetService.ListDataItems]
    /// may be used. If a single DataItem is matched by more than one of the
    /// FilterSplit filters, then it is assigned to the first set that applies to
    /// it in the training, validation, test order.
    ///
    /// [google.cloud.aiplatform.v1.DatasetService.ListDataItems]: <doc:DatasetServiceClient/listDataItems(request:options:)>
    public var testFilter: Swift.String = Swift.String()

    /// Initialize a new instance of `FilterSplit`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FilterSplit().with { $0.trainingFilter = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.FilterSplit"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
