// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if JobService
  import Foundation
  import GoogleCloudWkt
  import GoogleRpc

  /// Represents a HyperparameterTuningJob. A HyperparameterTuningJob
  /// has a Study specification and multiple CustomJobs with identical
  /// CustomJob specification.
  public struct HyperparameterTuningJob: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Resource name of the HyperparameterTuningJob.
    public var name: Swift.String = Swift.String()

    /// Required. The display name of the HyperparameterTuningJob.
    /// The name can be up to 128 characters long and can consist of any UTF-8
    /// characters.
    public var displayName: Swift.String = Swift.String()

    /// Required. Study configuration of the HyperparameterTuningJob.
    public var studySpec: StudySpec? = nil

    /// Required. The desired total number of Trials.
    public var maxTrialCount: Swift.Int32 = Swift.Int32()

    /// Required. The desired number of Trials to run in parallel.
    public var parallelTrialCount: Swift.Int32 = Swift.Int32()

    /// The number of failed Trials that need to be seen before failing
    /// the HyperparameterTuningJob.
    ///
    /// If set to 0, Vertex AI decides how many Trials must fail
    /// before the whole job fails.
    public var maxFailedTrialCount: Swift.Int32 = Swift.Int32()

    /// Required. The spec of a trial job. The same spec applies to the CustomJobs
    /// created in all the trials.
    public var trialJobSpec: CustomJobSpec? = nil

    /// Output only. Trials of the HyperparameterTuningJob.
    public var trials: [Trial] = []

    /// Output only. The detailed state of the job.
    public var state: JobState = JobState()

    /// Output only. Time when the HyperparameterTuningJob was created.
    public var createTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. Time when the HyperparameterTuningJob for the first time
    /// entered the `JOB_STATE_RUNNING` state.
    public var startTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. Time when the HyperparameterTuningJob entered any of the
    /// following states: `JOB_STATE_SUCCEEDED`, `JOB_STATE_FAILED`,
    /// `JOB_STATE_CANCELLED`.
    public var endTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. Time when the HyperparameterTuningJob was most recently
    /// updated.
    public var updateTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. Only populated when job's state is JOB_STATE_FAILED or
    /// JOB_STATE_CANCELLED.
    public var error: GoogleRpc.Status? = nil

    /// The labels with user-defined metadata to organize HyperparameterTuningJobs.
    ///
    /// Label keys and values can be no longer than 64 characters
    /// (Unicode codepoints), can only contain lowercase letters, numeric
    /// characters, underscores and dashes. International characters are allowed.
    ///
    /// See https://goo.gl/xmQnxf for more information and examples of labels.
    public var labels: [Swift.String: Swift.String] = [:]

    /// Customer-managed encryption key options for a HyperparameterTuningJob.
    /// If this is set, then all resources created by the HyperparameterTuningJob
    /// will be encrypted with the provided encryption key.
    public var encryptionSpec: EncryptionSpec? = nil

    /// Output only. Reserved for future use.
    public var satisfiesPzs: Swift.Bool = Swift.Bool()

    /// Output only. Reserved for future use.
    public var satisfiesPzi: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `HyperparameterTuningJob`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = HyperparameterTuningJob().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.HyperparameterTuningJob"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
