// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FeaturestoreService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Response message for
  /// [FeaturestoreService.ImportFeatureValues][google.cloud.aiplatform.v1.FeaturestoreService.ImportFeatureValues].
  ///
  /// [google.cloud.aiplatform.v1.FeaturestoreService.ImportFeatureValues]: <doc:FeaturestoreServiceClient/importFeatureValues(request:options:)>
  public struct ImportFeatureValuesResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Number of entities that have been imported by the operation.
    public var importedEntityCount: Swift.Int64 = Swift.Int64()

    /// Number of Feature values that have been imported by the operation.
    public var importedFeatureValueCount: Swift.Int64 = Swift.Int64()

    /// The number of rows in input source that weren't imported due to either
    /// * Not having any featureValues.
    /// * Having a null entityId.
    /// * Having a null timestamp.
    /// * Not being parsable (applicable for CSV sources).
    public var invalidRowCount: Swift.Int64 = Swift.Int64()

    /// The number rows that weren't ingested due to having feature timestamps
    /// outside the retention boundary.
    public var timestampOutsideRetentionRowsCount: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `ImportFeatureValuesResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportFeatureValuesResponse().with { $0.importedEntityCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ImportFeatureValuesResponse"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
