// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if JobService
  import Foundation
  import GoogleCloudLocation
  import GoogleCloudWkt
  import GoogleIAMV1
  import GoogleLongRunning
  import GoogleRpc
  import GoogleCloudGax

  extension Clients {
    protocol JobServiceStub: Sendable {
      func createCustomJob(
        request: CreateCustomJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.CustomJob

      func getCustomJob(
        request: GetCustomJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.CustomJob

      func listCustomJobs(
        request: ListCustomJobsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListCustomJobsResponse

      func deleteCustomJob(
        request: DeleteCustomJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func cancelCustomJob(
        request: CancelCustomJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func createDataLabelingJob(
        request: CreateDataLabelingJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.DataLabelingJob

      func getDataLabelingJob(
        request: GetDataLabelingJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.DataLabelingJob

      func listDataLabelingJobs(
        request: ListDataLabelingJobsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListDataLabelingJobsResponse

      func deleteDataLabelingJob(
        request: DeleteDataLabelingJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func cancelDataLabelingJob(
        request: CancelDataLabelingJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func createHyperparameterTuningJob(
        request: CreateHyperparameterTuningJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.HyperparameterTuningJob

      func getHyperparameterTuningJob(
        request: GetHyperparameterTuningJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.HyperparameterTuningJob

      func listHyperparameterTuningJobs(
        request: ListHyperparameterTuningJobsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListHyperparameterTuningJobsResponse

      func deleteHyperparameterTuningJob(
        request: DeleteHyperparameterTuningJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func cancelHyperparameterTuningJob(
        request: CancelHyperparameterTuningJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func createNasJob(
        request: CreateNasJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.NasJob

      func getNasJob(
        request: GetNasJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.NasJob

      func listNasJobs(
        request: ListNasJobsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListNasJobsResponse

      func deleteNasJob(
        request: DeleteNasJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func cancelNasJob(
        request: CancelNasJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func getNasTrialDetail(
        request: GetNasTrialDetailRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.NasTrialDetail

      func listNasTrialDetails(
        request: ListNasTrialDetailsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListNasTrialDetailsResponse

      func createBatchPredictionJob(
        request: CreateBatchPredictionJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.BatchPredictionJob

      func getBatchPredictionJob(
        request: GetBatchPredictionJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.BatchPredictionJob

      func listBatchPredictionJobs(
        request: ListBatchPredictionJobsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListBatchPredictionJobsResponse

      func deleteBatchPredictionJob(
        request: DeleteBatchPredictionJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func cancelBatchPredictionJob(
        request: CancelBatchPredictionJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func createModelDeploymentMonitoringJob(
        request: CreateModelDeploymentMonitoringJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ModelDeploymentMonitoringJob

      func searchModelDeploymentMonitoringStatsAnomalies(
        request: SearchModelDeploymentMonitoringStatsAnomaliesRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws
        -> GoogleCloudAIPlatformV1.SearchModelDeploymentMonitoringStatsAnomaliesResponse

      func getModelDeploymentMonitoringJob(
        request: GetModelDeploymentMonitoringJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ModelDeploymentMonitoringJob

      func listModelDeploymentMonitoringJobs(
        request: ListModelDeploymentMonitoringJobsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListModelDeploymentMonitoringJobsResponse

      func updateModelDeploymentMonitoringJob(
        request: UpdateModelDeploymentMonitoringJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func deleteModelDeploymentMonitoringJob(
        request: DeleteModelDeploymentMonitoringJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func pauseModelDeploymentMonitoringJob(
        request: PauseModelDeploymentMonitoringJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func resumeModelDeploymentMonitoringJob(
        request: ResumeModelDeploymentMonitoringJobRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      func setIamPolicy(
        request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      func getIamPolicy(
        request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      func testIamPermissions(
        request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func deleteOperation(
        request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func waitOperation(
        request: GoogleLongRunning.WaitOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation
    }
  }
#endif
