// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if VizierService
  import Foundation
  import GoogleCloudGax
  import GoogleCloudWkt

  /// Response message for
  /// [VizierService.ListTrials][google.cloud.aiplatform.v1.VizierService.ListTrials].
  ///
  /// [google.cloud.aiplatform.v1.VizierService.ListTrials]: <doc:VizierServiceClient/listTrials(request:options:)>
  public struct ListTrialsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    GoogleCloudGax._PaginatedResponse,
    Sendable
  {
    /// The Trials associated with the Study.
    public var trials: [Trial] = []

    /// Pass this token as the `page_token` field of the request for a
    /// subsequent call.
    /// If this field is omitted, there are no subsequent pages.
    public var nextPageToken: Swift.String = Swift.String()

    /// Initialize a new instance of `ListTrialsResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListTrialsResponse().with { $0.trials = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListTrialsResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [Trial] {
      return self.trials
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
