// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if IndexEndpointService
  import Foundation
  import GoogleCloudWkt

  /// Request message for
  /// [IndexEndpointService.ListIndexEndpoints][google.cloud.aiplatform.v1.IndexEndpointService.ListIndexEndpoints].
  ///
  /// [google.cloud.aiplatform.v1.IndexEndpointService.ListIndexEndpoints]: <doc:IndexEndpointServiceClient/listIndexEndpoints(request:options:)>
  public struct ListIndexEndpointsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the Location from which to list the
    /// IndexEndpoints. Format: `projects/{project}/locations/{location}`
    public var parent: Swift.String = Swift.String()

    /// Optional. An expression for filtering the results of the request. For field
    /// names both snake_case and camelCase are supported.
    ///
    ///   * `index_endpoint` supports = and !=. `index_endpoint` represents the
    ///      IndexEndpoint ID, ie. the last segment of the IndexEndpoint's
    ///      [resourcename][google.cloud.aiplatform.v1.IndexEndpoint.name].
    ///   * `display_name` supports =, != and regex()
    ///             (uses [re2](https://github.com/google/re2/wiki/Syntax) syntax)
    ///   * `labels` supports general map functions that is:
    ///             `labels.key=value` - key:value equality
    ///             `labels.key:* or labels:key - key existence
    ///              A key including a space must be quoted. `labels."a key"`.
    ///
    /// Some examples:
    ///   * `index_endpoint="1"`
    ///   * `display_name="myDisplayName"`
    ///   * `regex(display_name, "^A") -> The display name starts with an A.
    ///   * `labels.myKey="myValue"`
    ///
    /// [google.cloud.aiplatform.v1.IndexEndpoint.name]: <doc:IndexEndpoint/name>
    public var filter: Swift.String = Swift.String()

    /// Optional. The standard list page size.
    public var pageSize: Swift.Int32 = Swift.Int32()

    /// Optional. The standard list page token.
    /// Typically obtained via
    /// [ListIndexEndpointsResponse.next_page_token][google.cloud.aiplatform.v1.ListIndexEndpointsResponse.next_page_token]
    /// of the previous
    /// [IndexEndpointService.ListIndexEndpoints][google.cloud.aiplatform.v1.IndexEndpointService.ListIndexEndpoints]
    /// call.
    ///
    /// [google.cloud.aiplatform.v1.IndexEndpointService.ListIndexEndpoints]: <doc:IndexEndpointServiceClient/listIndexEndpoints(request:options:)>
    /// [google.cloud.aiplatform.v1.ListIndexEndpointsResponse.next_page_token]: <doc:ListIndexEndpointsResponse/nextPageToken>
    public var pageToken: Swift.String = Swift.String()

    /// Optional. Mask specifying which fields to read.
    public var readMask: GoogleCloudWkt.FieldMask? = nil

    /// Initialize a new instance of `ListIndexEndpointsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListIndexEndpointsRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListIndexEndpointsRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
