// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if NotebookService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Request message for [NotebookService.ListNotebookExecutionJobs]
  public struct ListNotebookExecutionJobsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the Location from which to list the
    /// NotebookExecutionJobs.
    /// Format: `projects/{project}/locations/{location}`
    public var parent: Swift.String = Swift.String()

    /// Optional. An expression for filtering the results of the request. For field
    /// names both snake_case and camelCase are supported.
    ///
    ///   * `notebookExecutionJob` supports = and !=. `notebookExecutionJob`
    ///   represents the NotebookExecutionJob ID.
    ///   * `displayName` supports = and != and regex.
    ///   * `schedule` supports = and != and regex.
    ///
    /// Some examples:
    ///   * `notebookExecutionJob="123"`
    ///   * `notebookExecutionJob="my-execution-job"`
    ///   * `displayName="myDisplayName"` and `displayName=~"myDisplayNameRegex"`
    public var filter: Swift.String = Swift.String()

    /// Optional. The standard list page size.
    public var pageSize: Swift.Int32 = Swift.Int32()

    /// Optional. The standard list page token.
    /// Typically obtained via
    /// [ListNotebookExecutionJobsResponse.next_page_token][google.cloud.aiplatform.v1.ListNotebookExecutionJobsResponse.next_page_token]
    /// of the previous
    /// [NotebookService.ListNotebookExecutionJobs][google.cloud.aiplatform.v1.NotebookService.ListNotebookExecutionJobs]
    /// call.
    ///
    /// [google.cloud.aiplatform.v1.ListNotebookExecutionJobsResponse.next_page_token]: <doc:ListNotebookExecutionJobsResponse/nextPageToken>
    /// [google.cloud.aiplatform.v1.NotebookService.ListNotebookExecutionJobs]: <doc:NotebookServiceClient/listNotebookExecutionJobs(request:options:)>
    public var pageToken: Swift.String = Swift.String()

    /// Optional. A comma-separated list of fields to order by, sorted in ascending
    /// order. Use "desc" after a field name for descending. Supported fields:
    ///
    ///   * `display_name`
    ///   * `create_time`
    ///   * `update_time`
    ///
    /// Example: `display_name, create_time desc`.
    public var orderBy: Swift.String = Swift.String()

    /// Optional. The NotebookExecutionJob view. Defaults to BASIC.
    public var view: NotebookExecutionJobView = NotebookExecutionJobView()

    /// Initialize a new instance of `ListNotebookExecutionJobsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListNotebookExecutionJobsRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListNotebookExecutionJobsRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
