// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PipelineService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudGax
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Response message for
  /// [PipelineService.ListTrainingPipelines][google.cloud.aiplatform.v1.PipelineService.ListTrainingPipelines]
  ///
  /// [google.cloud.aiplatform.v1.PipelineService.ListTrainingPipelines]: <doc:PipelineServiceClient/listTrainingPipelines(request:options:)>
  public struct ListTrainingPipelinesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    GoogleCloudGax._PaginatedResponse,
    Sendable
  {
    /// List of TrainingPipelines in the requested page.
    public var trainingPipelines: [TrainingPipeline] = []

    /// A token to retrieve the next page of results.
    /// Pass to
    /// [ListTrainingPipelinesRequest.page_token][google.cloud.aiplatform.v1.ListTrainingPipelinesRequest.page_token]
    /// to obtain that page.
    ///
    /// [google.cloud.aiplatform.v1.ListTrainingPipelinesRequest.page_token]: <doc:ListTrainingPipelinesRequest/pageToken>
    public var nextPageToken: Swift.String = Swift.String()

    /// Initialize a new instance of `ListTrainingPipelinesResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListTrainingPipelinesResponse().with { $0.trainingPipelines = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListTrainingPipelinesResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [TrainingPipeline] {
      return self.trainingPipelines
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
