// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if MetadataService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudGax
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Response message for
  /// [MetadataService.ListMetadataSchemas][google.cloud.aiplatform.v1.MetadataService.ListMetadataSchemas].
  ///
  /// [google.cloud.aiplatform.v1.MetadataService.ListMetadataSchemas]: <doc:MetadataServiceClient/listMetadataSchemas(request:options:)>
  public struct ListMetadataSchemasResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    GoogleCloudGax._PaginatedResponse,
    Sendable
  {
    /// The MetadataSchemas found for the MetadataStore.
    public var metadataSchemas: [MetadataSchema] = []

    /// A token, which can be sent as
    /// [ListMetadataSchemasRequest.page_token][google.cloud.aiplatform.v1.ListMetadataSchemasRequest.page_token]
    /// to retrieve the next page. If this field is not populated, there are no
    /// subsequent pages.
    ///
    /// [google.cloud.aiplatform.v1.ListMetadataSchemasRequest.page_token]: <doc:ListMetadataSchemasRequest/pageToken>
    public var nextPageToken: Swift.String = Swift.String()

    /// Initialize a new instance of `ListMetadataSchemasResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListMetadataSchemasResponse().with { $0.metadataSchemas = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListMetadataSchemasResponse"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [MetadataSchema] {
      return self.metadataSchemas
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
