// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if JobService
  import Foundation
  import GoogleCloudWkt

  /// Request message for
  /// [JobService.ListDataLabelingJobs][google.cloud.aiplatform.v1.JobService.ListDataLabelingJobs].
  ///
  /// [google.cloud.aiplatform.v1.JobService.ListDataLabelingJobs]: <doc:JobServiceClient/listDataLabelingJobs(request:options:)>
  public struct ListDataLabelingJobsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The parent of the DataLabelingJob.
    /// Format: `projects/{project}/locations/{location}`
    public var parent: Swift.String = Swift.String()

    /// The standard list filter.
    ///
    /// Supported fields:
    ///
    ///   * `display_name` supports `=`, `!=` comparisons, and `:` wildcard.
    ///   * `state` supports `=`, `!=` comparisons.
    ///   * `create_time` supports `=`, `!=`,`<`, `<=`,`>`, `>=` comparisons.
    ///     `create_time` must be in RFC 3339 format.
    ///   * `labels` supports general map functions that is:
    ///     `labels.key=value` - key:value equality
    ///     `labels.key:* - key existence
    ///
    /// Some examples of using the filter are:
    ///
    ///   * `state="JOB_STATE_SUCCEEDED" AND display_name:"my_job_*"`
    ///   * `state!="JOB_STATE_FAILED" OR display_name="my_job"`
    ///   * `NOT display_name="my_job"`
    ///   * `create_time>"2021-05-18T00:00:00Z"`
    ///   * `labels.keyA=valueA`
    ///   * `labels.keyB:*`
    public var filter: Swift.String = Swift.String()

    /// The standard list page size.
    public var pageSize: Swift.Int32 = Swift.Int32()

    /// The standard list page token.
    public var pageToken: Swift.String = Swift.String()

    /// Mask specifying which fields to read. FieldMask represents a set of
    /// symbolic field paths. For example, the mask can be `paths: "name"`. The
    /// "name" here is a field in DataLabelingJob.
    /// If this field is not set, all fields of the DataLabelingJob are returned.
    public var readMask: GoogleCloudWkt.FieldMask? = nil

    /// A comma-separated list of fields to order by, sorted in ascending order by
    /// default.
    /// Use `desc` after a field name for descending.
    public var orderBy: Swift.String = Swift.String()

    /// Initialize a new instance of `ListDataLabelingJobsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListDataLabelingJobsRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListDataLabelingJobsRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
