// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if NotebookService
  import Foundation
  import GoogleCloudWkt

  /// Request message for
  /// [NotebookService.ListNotebookRuntimeTemplates][google.cloud.aiplatform.v1.NotebookService.ListNotebookRuntimeTemplates].
  ///
  /// [google.cloud.aiplatform.v1.NotebookService.ListNotebookRuntimeTemplates]: <doc:NotebookServiceClient/listNotebookRuntimeTemplates(request:options:)>
  public struct ListNotebookRuntimeTemplatesRequest: Codable, Equatable, GoogleCloudWkt
      ._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the Location from which to list the
    /// NotebookRuntimeTemplates.
    /// Format: `projects/{project}/locations/{location}`
    public var parent: Swift.String = Swift.String()

    /// Optional. An expression for filtering the results of the request. For field
    /// names both snake_case and camelCase are supported.
    ///
    ///   * `notebookRuntimeTemplate` supports = and !=. `notebookRuntimeTemplate`
    ///     represents the NotebookRuntimeTemplate ID,
    ///     i.e. the last segment of the NotebookRuntimeTemplate's [resource name]
    ///     [google.cloud.aiplatform.v1.NotebookRuntimeTemplate.name].
    ///   * `display_name` supports = and !=
    ///   * `labels` supports general map functions that is:
    ///     * `labels.key=value` - key:value equality
    ///     * `labels.key:* or labels:key - key existence
    ///     * A key including a space must be quoted. `labels."a key"`.
    ///   * `notebookRuntimeType` supports = and !=. notebookRuntimeType enum:
    ///   [USER_DEFINED, ONE_CLICK].
    ///   * `machineType` supports = and !=.
    ///   * `acceleratorType` supports = and !=.
    ///
    /// Some examples:
    ///
    ///   * `notebookRuntimeTemplate=notebookRuntimeTemplate123`
    ///   * `displayName="myDisplayName"`
    ///   * `labels.myKey="myValue"`
    ///   * `notebookRuntimeType=USER_DEFINED`
    ///   * `machineType=e2-standard-4`
    ///   * `acceleratorType=NVIDIA_TESLA_T4`
    public var filter: Swift.String = Swift.String()

    /// Optional. The standard list page size.
    public var pageSize: Swift.Int32 = Swift.Int32()

    /// Optional. The standard list page token.
    /// Typically obtained via
    /// [ListNotebookRuntimeTemplatesResponse.next_page_token][google.cloud.aiplatform.v1.ListNotebookRuntimeTemplatesResponse.next_page_token]
    /// of the previous
    /// [NotebookService.ListNotebookRuntimeTemplates][google.cloud.aiplatform.v1.NotebookService.ListNotebookRuntimeTemplates]
    /// call.
    ///
    /// [google.cloud.aiplatform.v1.ListNotebookRuntimeTemplatesResponse.next_page_token]: <doc:ListNotebookRuntimeTemplatesResponse/nextPageToken>
    /// [google.cloud.aiplatform.v1.NotebookService.ListNotebookRuntimeTemplates]: <doc:NotebookServiceClient/listNotebookRuntimeTemplates(request:options:)>
    public var pageToken: Swift.String = Swift.String()

    /// Optional. Mask specifying which fields to read.
    public var readMask: GoogleCloudWkt.FieldMask? = nil

    /// Optional. A comma-separated list of fields to order by, sorted in ascending
    /// order. Use "desc" after a field name for descending. Supported fields:
    ///
    ///   * `display_name`
    ///   * `create_time`
    ///   * `update_time`
    ///
    /// Example: `display_name, create_time desc`.
    public var orderBy: Swift.String = Swift.String()

    /// Initialize a new instance of `ListNotebookRuntimeTemplatesRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListNotebookRuntimeTemplatesRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListNotebookRuntimeTemplatesRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
