// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ModelService
  import Foundation
  import GoogleCloudGax
  import GoogleCloudWkt

  /// Response message for
  /// [ModelService.ListModelEvaluationSlices][google.cloud.aiplatform.v1.ModelService.ListModelEvaluationSlices].
  ///
  /// [google.cloud.aiplatform.v1.ModelService.ListModelEvaluationSlices]: <doc:ModelServiceClient/listModelEvaluationSlices(request:)>
  public struct ListModelEvaluationSlicesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    GoogleCloudGax._PaginatedResponse,
    Sendable
  {
    /// List of ModelEvaluations in the requested page.
    public var modelEvaluationSlices: [ModelEvaluationSlice] = []

    /// A token to retrieve next page of results.
    /// Pass to
    /// [ListModelEvaluationSlicesRequest.page_token][google.cloud.aiplatform.v1.ListModelEvaluationSlicesRequest.page_token]
    /// to obtain that page.
    ///
    /// [google.cloud.aiplatform.v1.ListModelEvaluationSlicesRequest.page_token]: <doc:ListModelEvaluationSlicesRequest/pageToken>
    public var nextPageToken: Swift.String = Swift.String()

    /// Initialize a new instance of `ListModelEvaluationSlicesResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListModelEvaluationSlicesResponse().with { $0.modelEvaluationSlices = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListModelEvaluationSlicesResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [ModelEvaluationSlice] {
      return self.modelEvaluationSlices
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
