// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if MetadataService
  import Foundation
  import GoogleCloudGax
  import GoogleCloudWkt

  /// Response message for
  /// [MetadataService.ListArtifacts][google.cloud.aiplatform.v1.MetadataService.ListArtifacts].
  ///
  /// [google.cloud.aiplatform.v1.MetadataService.ListArtifacts]: <doc:MetadataService/listArtifacts(request:)>
  public struct ListArtifactsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    GoogleCloudGax._PaginatedResponse,
    Sendable
  {
    /// The Artifacts retrieved from the MetadataStore.
    public var artifacts: [Artifact] = []

    /// A token, which can be sent as
    /// [ListArtifactsRequest.page_token][google.cloud.aiplatform.v1.ListArtifactsRequest.page_token]
    /// to retrieve the next page.
    /// If this field is not populated, there are no subsequent pages.
    ///
    /// [google.cloud.aiplatform.v1.ListArtifactsRequest.page_token]: <doc:ListArtifactsRequest/pageToken>
    public var nextPageToken: Swift.String = Swift.String()

    /// Initialize a new instance of `ListArtifactsResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListArtifactsResponse().with { $0.artifacts = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.ListArtifactsResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [Artifact] {
      return self.artifacts
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
