// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PredictionService
  import Foundation
  import GoogleCloudWkt

  /// Logprobs Result
  public struct LogprobsResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Length = total number of decoding steps.
    public var topCandidates: [LogprobsResult.TopCandidates] = []

    /// Length = total number of decoding steps.
    /// The chosen candidates may or may not be in top_candidates.
    public var chosenCandidates: [LogprobsResult.Candidate] = []

    /// Initialize a new instance of `LogprobsResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LogprobsResult().with { $0.topCandidates = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Candidate for the logprobs token and score.
    public struct Candidate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The candidate’s token string value.
      public var token: Swift.String? = nil

      /// The candidate’s token id value.
      public var tokenId: Swift.Int32? = nil

      /// The candidate's log probability.
      public var logProbability: Swift.Float? = nil

      /// Initialize a new instance of `Candidate`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Candidate().with { $0.token = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.LogprobsResult.Candidate"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Candidates with top log probabilities at each decoding step.
    public struct TopCandidates: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Sorted by log probability in descending order.
      public var candidates: [LogprobsResult.Candidate] = []

      /// Initialize a new instance of `TopCandidates`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TopCandidates().with { $0.candidates = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.LogprobsResult.TopCandidates"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.LogprobsResult"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
