// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if JobService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Represents a mount configuration for Lustre file system.
  public struct LustreMount: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. IP address of the Lustre instance.
    public var instanceIp: Swift.String = Swift.String()

    /// Required. The unique identifier of the Lustre volume.
    public var volumeHandle: Swift.String = Swift.String()

    /// Required. The name of the Lustre filesystem.
    public var filesystem: Swift.String = Swift.String()

    /// Required. Destination mount path. The Lustre file system will be mounted
    /// for the user under /mnt/lustre/<mount_point>
    public var mountPoint: Swift.String = Swift.String()

    /// Initialize a new instance of `LustreMount`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LustreMount().with { $0.instanceIp = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.LustreMount"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
