// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FeatureOnlineStoreService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// A query to find a number of similar entities.
  public struct NearestNeighborQuery: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The number of similar entities to be retrieved from feature view
    /// for each query.
    public var neighborCount: Swift.Int32 = Swift.Int32()

    /// Optional. The list of string filters.
    public var stringFilters: [NearestNeighborQuery.StringFilter] = []

    /// Optional. The list of numeric filters.
    public var numericFilters: [NearestNeighborQuery.NumericFilter] = []

    /// Optional. Crowding is a constraint on a neighbor list produced by nearest
    /// neighbor search requiring that no more than
    /// sper_crowding_attribute_neighbor_count of the k neighbors returned have the
    /// same value of crowding_attribute. It's used for improving result diversity.
    public var perCrowdingAttributeNeighborCount: Swift.Int32 = Swift.Int32()

    /// Optional. Parameters that can be set to tune query on the fly.
    public var parameters: NearestNeighborQuery.Parameters? = nil

    public var instance: OneOf_Instance? = nil

    /// Initialize a new instance of `NearestNeighborQuery`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NearestNeighborQuery().with { $0.entityId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case entityId = "entityId"
      case embedding = "embedding"
      case neighborCount = "neighborCount"
      case stringFilters = "stringFilters"
      case numericFilters = "numericFilters"
      case perCrowdingAttributeNeighborCount = "perCrowdingAttributeNeighborCount"
      case parameters = "parameters"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.neighborCount = try container.decode(Swift.Int32.self, forKey: .neighborCount)
      self.stringFilters = try container.decode(
        [NearestNeighborQuery.StringFilter].self, forKey: .stringFilters)
      self.numericFilters = try container.decode(
        [NearestNeighborQuery.NumericFilter].self, forKey: .numericFilters)
      self.perCrowdingAttributeNeighborCount = try container.decode(
        Swift.Int32.self, forKey: .perCrowdingAttributeNeighborCount)
      self.parameters = try container.decodeIfPresent(
        NearestNeighborQuery.Parameters.self, forKey: .parameters)

      var instance: OneOf_Instance? = nil
      let instanceCheckAndSet = {
        if instance != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'instance'"))
        }
        instance = $0
      }
      if let entityId = try container.decodeIfPresent(Swift.String.self, forKey: .entityId) {
        try instanceCheckAndSet(.entityId(entityId))
      }
      if let embedding = try container.decodeIfPresent(
        NearestNeighborQuery.Embedding?.self, forKey: .embedding)
      {
        try instanceCheckAndSet(.embedding(embedding))
      }
      self.instance = instance
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.neighborCount, forKey: .neighborCount)
      try container.encode(self.stringFilters, forKey: .stringFilters)
      try container.encode(self.numericFilters, forKey: .numericFilters)
      try container.encode(
        self.perCrowdingAttributeNeighborCount, forKey: .perCrowdingAttributeNeighborCount)
      try container.encode(self.parameters, forKey: .parameters)

      if let choice = self.instance {
        switch choice {
        case .entityId(let value):
          try container.encode(value, forKey: .entityId)
        case .embedding(let value):
          try container.encode(value, forKey: .embedding)
        }
      }
    }

    /// The embedding vector.
    public struct Embedding: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. Individual value in the embedding.
      public var value: [Swift.Float] = []

      /// Initialize a new instance of `Embedding`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Embedding().with { $0.value = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.NearestNeighborQuery.Embedding"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// String filter is used to search a subset of the entities by using boolean
    /// rules on string columns.
    /// For example: if a query specifies string filter
    /// with 'name = color, allow_tokens = {red, blue}, deny_tokens = {purple}','
    /// then that query will match entities that are red or blue, but if those
    /// points are also purple, then they will be excluded even if they are
    /// red/blue. Only string filter is supported for now, numeric filter will be
    /// supported in the near future.
    public struct StringFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Column names in BigQuery that used as filters.
      public var name: Swift.String = Swift.String()

      /// Optional. The allowed tokens.
      public var allowTokens: [Swift.String] = []

      /// Optional. The denied tokens.
      public var denyTokens: [Swift.String] = []

      /// Initialize a new instance of `StringFilter`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = StringFilter().with { $0.name = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.NearestNeighborQuery.StringFilter"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Numeric filter is used to search a subset of the entities by using boolean
    /// rules on numeric columns.
    /// For example:
    /// Database Point 0: {name: "a" value_int: 42} {name: "b" value_float: 1.0}
    /// Database Point 1:  {name: "a" value_int: 10} {name: "b" value_float: 2.0}
    /// Database Point 2: {name: "a" value_int: -1} {name: "b" value_float: 3.0}
    /// Query: {name: "a" value_int: 12 operator: LESS}    // Matches Point 1, 2
    /// {name: "b" value_float: 2.0 operator: EQUAL} // Matches Point 1
    public struct NumericFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Column name in BigQuery that used as filters.
      public var name: Swift.String = Swift.String()

      /// Optional. This MUST be specified for queries and must NOT be specified
      /// for database points.
      public var op: NearestNeighborQuery.NumericFilter.Operator? = nil

      /// The type of Value must be consistent for all datapoints with a given
      /// name.  This is verified at runtime.
      public var value: OneOf_Value? = nil

      /// Initialize a new instance of `NumericFilter`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = NumericFilter().with { $0.valueInt = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case valueInt = "valueInt"
        case valueFloat = "valueFloat"
        case valueDouble = "valueDouble"
        case name = "name"
        case op = "op"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.name = try container.decode(Swift.String.self, forKey: .name)
        self.op = try container.decodeIfPresent(
          NearestNeighborQuery.NumericFilter.Operator.self, forKey: .op)

        var value: OneOf_Value? = nil
        let valueCheckAndSet = {
          if value != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'value'"))
          }
          value = $0
        }
        if let valueInt = try container.decodeIfPresent(Swift.Int64.self, forKey: .valueInt) {
          try valueCheckAndSet(.valueInt(valueInt))
        }
        if let valueFloat = try container.decodeIfPresent(Swift.Float.self, forKey: .valueFloat) {
          try valueCheckAndSet(.valueFloat(valueFloat))
        }
        if let valueDouble = try container.decodeIfPresent(Swift.Double.self, forKey: .valueDouble)
        {
          try valueCheckAndSet(.valueDouble(valueDouble))
        }
        self.value = value
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.op, forKey: .op)

        if let choice = self.value {
          switch choice {
          case .valueInt(let value):
            try container.encode(value, forKey: .valueInt)
          case .valueFloat(let value):
            try container.encode(value, forKey: .valueFloat)
          case .valueDouble(let value):
            try container.encode(value, forKey: .valueDouble)
          }
        }
      }

      /// Datapoints for which Operator is true relative to the query's Value
      /// field will be allowlisted.
      public enum Operator: Codable, Equatable, Sendable {
        /// Unspecified operator.
        case unspecified
        /// Entities are eligible if their value is < the query's.
        case less
        /// Entities are eligible if their value is <= the query's.
        case lessEqual
        /// Entities are eligible if their value is == the query's.
        case equal
        /// Entities are eligible if their value is >= the query's.
        case greaterEqual
        /// Entities are eligible if their value is > the query's.
        case greater
        /// Entities are eligible if their value is != the query's.
        case notEqual
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .less: return 1
          case .lessEqual: return 2
          case .equal: return 3
          case .greaterEqual: return 4
          case .greater: return 5
          case .notEqual: return 6
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "OPERATOR_UNSPECIFIED"
          case .less: return "LESS"
          case .lessEqual: return "LESS_EQUAL"
          case .equal: return "EQUAL"
          case .greaterEqual: return "GREATER_EQUAL"
          case .greater: return "GREATER"
          case .notEqual: return "NOT_EQUAL"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Operator/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "OPERATOR_UNSPECIFIED": self = .unspecified
          case "LESS": self = .less
          case "LESS_EQUAL": self = .lessEqual
          case "EQUAL": self = .equal
          case "GREATER_EQUAL": self = .greaterEqual
          case "GREATER": self = .greater
          case "NOT_EQUAL": self = .notEqual
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Operator/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .less
          case 2: self = .lessEqual
          case 3: self = .equal
          case 4: self = .greaterEqual
          case 5: self = .greater
          case 6: self = .notEqual
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .less: return try container.encode(1)
          case .lessEqual: return try container.encode(2)
          case .equal: return try container.encode(3)
          case .greaterEqual: return try container.encode(4)
          case .greater: return try container.encode(5)
          case .notEqual: return try container.encode(6)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      /// The type of Value must be consistent for all datapoints with a given
      /// name.  This is verified at runtime.
      public enum OneOf_Value: Codable, Equatable, Sendable {
        /// int value type.
        case valueInt(Swift.Int64)
        /// float value type.
        case valueFloat(Swift.Float)
        /// double value type.
        case valueDouble(Swift.Double)
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.NearestNeighborQuery.NumericFilter"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Parameters that can be overrided in each query to tune query latency and
    /// recall.
    public struct Parameters: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. The number of neighbors to find via approximate search before
      /// exact reordering is performed; if set, this value must be >
      /// neighbor_count.
      public var approximateNeighborCandidates: Swift.Int32 = Swift.Int32()

      /// Optional. The fraction of the number of leaves to search, set at query
      /// time allows user to tune search performance. This value increase result
      /// in both search accuracy and latency increase. The value should be between
      /// 0.0 and 1.0.
      public var leafNodesSearchFraction: Swift.Double = Swift.Double()

      /// Initialize a new instance of `Parameters`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Parameters().with { $0.approximateNeighborCandidates = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.NearestNeighborQuery.Parameters"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_Instance: Codable, Equatable, Sendable {
      /// Optional. The entity id whose similar entities should be searched for.
      /// If embedding is set, search will use embedding instead of
      /// entity_id.
      case entityId(Swift.String)
      /// Optional. The embedding vector that be used for similar search.
      indirect case embedding(NearestNeighborQuery.Embedding?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.NearestNeighborQuery"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
