// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FeatureOnlineStoreService
  import Foundation
  import GoogleCloudWkt

  /// Nearest neighbors for one query.
  public struct NearestNeighbors: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// All its neighbors.
    public var neighbors: [NearestNeighbors.Neighbor] = []

    /// Initialize a new instance of `NearestNeighbors`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NearestNeighbors().with { $0.neighbors = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// A neighbor of the query vector.
    public struct Neighbor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The id of the similar entity.
      public var entityId: Swift.String = Swift.String()

      /// The distance between the neighbor and the query vector.
      public var distance: Swift.Double = Swift.Double()

      /// The attributes of the neighbor, e.g. filters, crowding and metadata
      /// Note that full entities are returned only when "return_full_entity"
      /// is set to true. Otherwise, only the "entity_id" and "distance" fields
      /// are populated.
      public var entityKeyValues: FetchFeatureValuesResponse? = nil

      /// Initialize a new instance of `Neighbor`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Neighbor().with { $0.entityId = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.NearestNeighbors.Neighbor"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.NearestNeighbors"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
