// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if NotebookService
  import Foundation
  import GoogleCloudLocation
  import GoogleIAMV1
  import GoogleLongRunning
  import GoogleRpc
  import GoogleWKT
  import GoogleGax

  extension Clients {
    protocol NotebookServiceStub: Sendable {
      func createNotebookRuntimeTemplate(
        request: CreateNotebookRuntimeTemplateRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func getNotebookRuntimeTemplate(
        request: GetNotebookRuntimeTemplateRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.NotebookRuntimeTemplate

      func listNotebookRuntimeTemplates(
        request: ListNotebookRuntimeTemplatesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListNotebookRuntimeTemplatesResponse

      func deleteNotebookRuntimeTemplate(
        request: DeleteNotebookRuntimeTemplateRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func updateNotebookRuntimeTemplate(
        request: UpdateNotebookRuntimeTemplateRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.NotebookRuntimeTemplate

      func assignNotebookRuntime(
        request: AssignNotebookRuntimeRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func getNotebookRuntime(
        request: GetNotebookRuntimeRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.NotebookRuntime

      func listNotebookRuntimes(
        request: ListNotebookRuntimesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListNotebookRuntimesResponse

      func deleteNotebookRuntime(
        request: DeleteNotebookRuntimeRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func upgradeNotebookRuntime(
        request: UpgradeNotebookRuntimeRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func startNotebookRuntime(
        request: StartNotebookRuntimeRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func stopNotebookRuntime(
        request: StopNotebookRuntimeRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func createNotebookExecutionJob(
        request: CreateNotebookExecutionJobRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func getNotebookExecutionJob(
        request: GetNotebookExecutionJobRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.NotebookExecutionJob

      func listNotebookExecutionJobs(
        request: ListNotebookExecutionJobsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListNotebookExecutionJobsResponse

      func deleteNotebookExecutionJob(
        request: DeleteNotebookExecutionJobRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      func setIamPolicy(
        request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      func getIamPolicy(
        request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      func testIamPermissions(
        request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func deleteOperation(
        request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      func waitOperation(
        request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation
    }
  }
#endif
