// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PredictionService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleApi
  import GoogleCloudLocation
  import GoogleIAMV1
  import GoogleLongRunning
  import GoogleWKT
  @_spi(GoogleCloudInternal) import GoogleGax

  extension Clients {
    final class PredictionServiceRetry: PredictionServiceStub {
      let inner: any PredictionServiceStub
      let options: GoogleGax.ClientOptions

      public init(_ inner: any PredictionServiceStub, options: GoogleGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func predict(
        request: PredictRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.PredictResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: PredictRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.PredictResponse
            in
            return try await self.inner.predict(request: r, options: o)
          })
      }

      public func rawPredict(
        request: RawPredictRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleApi.HttpBody {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: RawPredictRequest, o: GoogleGax.RequestOptions) async throws -> GoogleApi.HttpBody
            in
            return try await self.inner.rawPredict(request: r, options: o)
          })
      }

      public func streamRawPredict(
        request: StreamRawPredictRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleApi.HttpBody {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: StreamRawPredictRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleApi.HttpBody
            in
            return try await self.inner.streamRawPredict(request: r, options: o)
          })
      }

      public func directPredict(
        request: DirectPredictRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.DirectPredictResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DirectPredictRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.DirectPredictResponse
            in
            return try await self.inner.directPredict(request: r, options: o)
          })
      }

      public func directRawPredict(
        request: DirectRawPredictRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.DirectRawPredictResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DirectRawPredictRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.DirectRawPredictResponse
            in
            return try await self.inner.directRawPredict(request: r, options: o)
          })
      }

      public func serverStreamingPredict(
        request: StreamingPredictRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.StreamingPredictResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: StreamingPredictRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.StreamingPredictResponse
            in
            return try await self.inner.serverStreamingPredict(request: r, options: o)
          })
      }

      public func explain(
        request: ExplainRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ExplainResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: ExplainRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ExplainResponse
            in
            return try await self.inner.explain(request: r, options: o)
          })
      }

      public func generateContent(
        request: GenerateContentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.GenerateContentResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GenerateContentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.GenerateContentResponse
            in
            return try await self.inner.generateContent(request: r, options: o)
          })
      }

      public func streamGenerateContent(
        request: GenerateContentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.GenerateContentResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GenerateContentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.GenerateContentResponse
            in
            return try await self.inner.streamGenerateContent(request: r, options: o)
          })
      }

      public func embedContent(
        request: EmbedContentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.EmbedContentResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: EmbedContentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.EmbedContentResponse
            in
            return try await self.inner.embedContent(request: r, options: o)
          })
      }

      public func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudLocation.ListLocationsResponse
            in
            return try await self.inner.listLocations(request: r, options: o)
          })
      }

      public func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudLocation.Location
            in
            return try await self.inner.getLocation(request: r, options: o)
          })
      }

      public func setIamPolicy(
        request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleIAMV1.Policy
            in
            return try await self.inner.setIamPolicy(request: r, options: o)
          })
      }

      public func getIamPolicy(
        request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleIAMV1.Policy
            in
            return try await self.inner.getIamPolicy(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleIAMV1.TestIamPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func deleteOperation(
        request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> Void in
            return try await self.inner.deleteOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }

      public func waitOperation(
        request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleLongRunning.WaitOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.waitOperation(request: r, options: o)
          })
      }
    }
  }
#endif
