// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GenAiTuningService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// A pre-tuned model for continuous tuning.
  public struct PreTunedModel: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The resource name of the Model.
    /// E.g., a model resource name with a specified version id or alias:
    ///
    /// `projects/{project}/locations/{location}/models/{model}@{version_id}`
    ///
    /// `projects/{project}/locations/{location}/models/{model}@{alias}`
    ///
    /// Or, omit the version id to use the default version:
    ///
    /// `projects/{project}/locations/{location}/models/{model}`
    public var tunedModelName: Swift.String = Swift.String()

    /// Optional. The source checkpoint id. If not specified, the default
    /// checkpoint will be used.
    public var checkpointId: Swift.String = Swift.String()

    /// Output only. The name of the base model this
    /// [PreTunedModel][google.cloud.aiplatform.v1.PreTunedModel] was tuned from.
    ///
    /// [google.cloud.aiplatform.v1.PreTunedModel]: <doc:PreTunedModel>
    public var baseModel: Swift.String = Swift.String()

    /// Initialize a new instance of `PreTunedModel`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PreTunedModel().with { $0.tunedModelName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.PreTunedModel"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
