// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ModelGardenService
  import Foundation
  import GoogleCloudWkt

  /// A Model Garden Publisher Model.
  public struct PublisherModel: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The resource name of the PublisherModel.
    public var name: Swift.String = Swift.String()

    /// Output only. Immutable. The version ID of the PublisherModel.
    /// A new version is committed when a new model version is uploaded under an
    /// existing model id. It is an auto-incrementing decimal number in string
    /// representation.
    public var versionId: Swift.String = Swift.String()

    /// Required. Indicates the open source category of the publisher model.
    public var openSourceCategory: PublisherModel.OpenSourceCategory =
      PublisherModel.OpenSourceCategory()

    /// Optional. Supported call-to-action options.
    public var supportedActions: PublisherModel.CallToAction? = nil

    /// Optional. Additional information about the model's Frameworks.
    public var frameworks: [Swift.String] = []

    /// Optional. Indicates the launch stage of the model.
    public var launchStage: PublisherModel.LaunchStage = PublisherModel.LaunchStage()

    /// Optional. Indicates the state of the model version.
    public var versionState: PublisherModel.VersionState = PublisherModel.VersionState()

    /// Optional. Output only. Immutable. Used to indicate this model has a
    /// publisher model and provide the template of the publisher model resource
    /// name.
    public var publisherModelTemplate: Swift.String = Swift.String()

    /// Optional. The schemata that describes formats of the PublisherModel's
    /// predictions and explanations as given and returned via
    /// [PredictionService.Predict][google.cloud.aiplatform.v1.PredictionService.Predict].
    ///
    /// [google.cloud.aiplatform.v1.PredictionService.Predict]: <doc:PredictionServiceClient/predict(request:options:)>
    public var predictSchemata: PredictSchemata? = nil

    /// Initialize a new instance of `PublisherModel`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PublisherModel().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Reference to a resource.
    public struct ResourceReference: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var reference: OneOf_Reference? = nil

      /// Initialize a new instance of `ResourceReference`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ResourceReference().with { $0.uri = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case uri = "uri"
        case resourceName = "resourceName"
        case useCase = "useCase"
        case description = "description"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var reference: OneOf_Reference? = nil
        let referenceCheckAndSet = {
          if reference != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'reference'"))
          }
          reference = $0
        }
        if let uri = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
          try referenceCheckAndSet(.uri(uri))
        }
        if let resourceName = try container.decodeIfPresent(
          Swift.String.self, forKey: .resourceName)
        {
          try referenceCheckAndSet(.resourceName(resourceName))
        }
        if let useCase = try container.decodeIfPresent(Swift.String.self, forKey: .useCase) {
          try referenceCheckAndSet(.useCase(useCase))
        }
        if let description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
        {
          try referenceCheckAndSet(.description(description))
        }
        self.reference = reference
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.reference {
          switch choice {
          case .uri(let value):
            try container.encode(value, forKey: .uri)
          case .resourceName(let value):
            try container.encode(value, forKey: .resourceName)
          case .useCase(let value):
            try container.encode(value, forKey: .useCase)
          case .description(let value):
            try container.encode(value, forKey: .description)
          }
        }
      }

      public enum OneOf_Reference: Codable, Equatable, Sendable {
        /// The URI of the resource.
        case uri(Swift.String)
        /// The resource name of the Google Cloud resource.
        case resourceName(Swift.String)
        /// Use case (CUJ) of the resource.
        @available(*, deprecated)
        case useCase(Swift.String)
        /// Description of the resource.
        @available(*, deprecated)
        case description(Swift.String)
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.ResourceReference"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// A named piece of documentation.
    public struct Documentation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. E.g., OVERVIEW, USE CASES, DOCUMENTATION, SDK & SAMPLES, JAVA,
      /// NODE.JS, etc..
      public var title: Swift.String = Swift.String()

      /// Required. Content of this piece of document (in Markdown format).
      public var content: Swift.String = Swift.String()

      /// Initialize a new instance of `Documentation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Documentation().with { $0.title = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.Documentation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Actions could take on this Publisher Model.
    public struct CallToAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. To view Rest API docs.
      public var viewRestApi: PublisherModel.CallToAction.ViewRestApi? = nil

      /// Optional. Open notebook of the PublisherModel.
      public var openNotebook: PublisherModel.CallToAction.RegionalResourceReferences? = nil

      /// Optional. Open notebooks of the PublisherModel.
      public var openNotebooks: PublisherModel.CallToAction.OpenNotebooks? = nil

      /// Optional. Create application using the PublisherModel.
      public var createApplication: PublisherModel.CallToAction.RegionalResourceReferences? = nil

      /// Optional. Open fine-tuning pipeline of the PublisherModel.
      public var openFineTuningPipeline: PublisherModel.CallToAction.RegionalResourceReferences? =
        nil

      /// Optional. Open fine-tuning pipelines of the PublisherModel.
      public var openFineTuningPipelines: PublisherModel.CallToAction.OpenFineTuningPipelines? = nil

      /// Optional. Open prompt-tuning pipeline of the PublisherModel.
      public var openPromptTuningPipeline: PublisherModel.CallToAction.RegionalResourceReferences? =
        nil

      /// Optional. Open Genie / Playground.
      public var openGenie: PublisherModel.CallToAction.RegionalResourceReferences? = nil

      /// Optional. Deploy the PublisherModel to Vertex Endpoint.
      public var deploy: PublisherModel.CallToAction.Deploy? = nil

      /// Optional. Deploy PublisherModel to Google Kubernetes Engine.
      public var deployGke: PublisherModel.CallToAction.DeployGke? = nil

      /// Optional. Open in Generation AI Studio.
      public var openGenerationAiStudio: PublisherModel.CallToAction.RegionalResourceReferences? =
        nil

      /// Optional. Request for access.
      public var requestAccess: PublisherModel.CallToAction.RegionalResourceReferences? = nil

      /// Optional. Open evaluation pipeline of the PublisherModel.
      public var openEvaluationPipeline: PublisherModel.CallToAction.RegionalResourceReferences? =
        nil

      /// Initialize a new instance of `CallToAction`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CallToAction().with { $0.viewRestApi = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// The regional resource name or the URI. Key is region, e.g.,
      /// us-central1, europe-west2, global, etc..
      public struct RegionalResourceReferences: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Required.
        public var references: [Swift.String: PublisherModel.ResourceReference] = [:]

        /// Required.
        public var title: Swift.String = Swift.String()

        /// Optional. Title of the resource.
        public var resourceTitle: Swift.String? = nil

        /// Optional. Use case (CUJ) of the resource.
        public var resourceUseCase: Swift.String? = nil

        /// Optional. Description of the resource.
        public var resourceDescription: Swift.String? = nil

        /// Initialize a new instance of `RegionalResourceReferences`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = RegionalResourceReferences().with { $0.references = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.CallToAction.RegionalResourceReferences"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// Rest API docs.
      public struct ViewRestApi: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Required.
        public var documentations: [PublisherModel.Documentation] = []

        /// Required. The title of the view rest API.
        public var title: Swift.String = Swift.String()

        /// Initialize a new instance of `ViewRestApi`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = ViewRestApi().with { $0.documentations = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.CallToAction.ViewRestApi"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// Open notebooks.
      public struct OpenNotebooks: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Required. Regional resource references to notebooks.
        public var notebooks: [PublisherModel.CallToAction.RegionalResourceReferences] = []

        /// Initialize a new instance of `OpenNotebooks`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = OpenNotebooks().with { $0.notebooks = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.CallToAction.OpenNotebooks"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// Open fine tuning pipelines.
      public struct OpenFineTuningPipelines: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Required. Regional resource references to fine tuning pipelines.
        public var fineTuningPipelines: [PublisherModel.CallToAction.RegionalResourceReferences] =
          []

        /// Initialize a new instance of `OpenFineTuningPipelines`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = OpenFineTuningPipelines().with { $0.fineTuningPipelines = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.CallToAction.OpenFineTuningPipelines"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// Model metadata that is needed for UploadModel or
      /// DeployModel/CreateEndpoint requests.
      public struct Deploy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Optional. Default model display name.
        public var modelDisplayName: Swift.String = Swift.String()

        /// Optional. Large model reference. When this is set, model_artifact_spec
        /// is not needed.
        public var largeModelReference: LargeModelReference? = nil

        /// Optional. The specification of the container that is to be used when
        /// deploying this Model in Vertex AI. Not present for Large Models.
        public var containerSpec: ModelContainerSpec? = nil

        /// Optional. The path to the directory containing the Model artifact and
        /// any of its supporting files.
        public var artifactUri: Swift.String = Swift.String()

        /// Optional. The name of the deploy task (e.g., "text to image
        /// generation").
        public var deployTaskName: Swift.String? = nil

        /// Optional. Metadata information about this deployment config.
        public var deployMetadata: PublisherModel.CallToAction.Deploy.DeployMetadata? = nil

        /// Required. The title of the regional resource reference.
        public var title: Swift.String = Swift.String()

        /// Optional. The signed URI for ephemeral Cloud Storage access to model
        /// artifact.
        public var publicArtifactUri: Swift.String = Swift.String()

        /// The prediction (for example, the machine) resources that the
        /// DeployedModel uses.
        public var predictionResources: OneOf_PredictionResources? = nil

        /// Initialize a new instance of `Deploy`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Deploy().with { $0.dedicatedResources = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private enum CodingKeys: Swift.String, CodingKey {
          case dedicatedResources = "dedicatedResources"
          case automaticResources = "automaticResources"
          case sharedResources = "sharedResources"
          case modelDisplayName = "modelDisplayName"
          case largeModelReference = "largeModelReference"
          case containerSpec = "containerSpec"
          case artifactUri = "artifactUri"
          case deployTaskName = "deployTaskName"
          case deployMetadata = "deployMetadata"
          case title = "title"
          case publicArtifactUri = "publicArtifactUri"
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          self.modelDisplayName = try container.decode(Swift.String.self, forKey: .modelDisplayName)
          self.largeModelReference = try container.decodeIfPresent(
            LargeModelReference.self, forKey: .largeModelReference)
          self.containerSpec = try container.decodeIfPresent(
            ModelContainerSpec.self, forKey: .containerSpec)
          self.artifactUri = try container.decode(Swift.String.self, forKey: .artifactUri)
          self.deployTaskName = try container.decodeIfPresent(
            Swift.String.self, forKey: .deployTaskName)
          self.deployMetadata = try container.decodeIfPresent(
            PublisherModel.CallToAction.Deploy.DeployMetadata.self, forKey: .deployMetadata)
          self.title = try container.decode(Swift.String.self, forKey: .title)
          self.publicArtifactUri = try container.decode(
            Swift.String.self, forKey: .publicArtifactUri)

          var predictionResources: OneOf_PredictionResources? = nil
          let predictionResourcesCheckAndSet = {
            if predictionResources != nil {
              throw DecodingError.dataCorrupted(
                DecodingError.Context(
                  codingPath: decoder.codingPath,
                  debugDescription: "Multiple values set for oneof 'predictionResources'"))
            }
            predictionResources = $0
          }
          if let dedicatedResources = try container.decodeIfPresent(
            DedicatedResources?.self, forKey: .dedicatedResources)
          {
            try predictionResourcesCheckAndSet(.dedicatedResources(dedicatedResources))
          }
          if let automaticResources = try container.decodeIfPresent(
            AutomaticResources?.self, forKey: .automaticResources)
          {
            try predictionResourcesCheckAndSet(.automaticResources(automaticResources))
          }
          if let sharedResources = try container.decodeIfPresent(
            Swift.String.self, forKey: .sharedResources)
          {
            try predictionResourcesCheckAndSet(.sharedResources(sharedResources))
          }
          self.predictionResources = predictionResources
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.modelDisplayName, forKey: .modelDisplayName)
          try container.encode(self.largeModelReference, forKey: .largeModelReference)
          try container.encode(self.containerSpec, forKey: .containerSpec)
          try container.encode(self.artifactUri, forKey: .artifactUri)
          try container.encode(self.deployTaskName, forKey: .deployTaskName)
          try container.encode(self.deployMetadata, forKey: .deployMetadata)
          try container.encode(self.title, forKey: .title)
          try container.encode(self.publicArtifactUri, forKey: .publicArtifactUri)

          if let choice = self.predictionResources {
            switch choice {
            case .dedicatedResources(let value):
              try container.encode(value, forKey: .dedicatedResources)
            case .automaticResources(let value):
              try container.encode(value, forKey: .automaticResources)
            case .sharedResources(let value):
              try container.encode(value, forKey: .sharedResources)
            }
          }
        }

        /// Metadata information about the deployment for managing deployment
        /// config.
        public struct DeployMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
          Sendable
        {
          /// Optional. Labels for the deployment. For managing deployment config
          /// like verifying, source of deployment config, etc.
          public var labels: [Swift.String: Swift.String] = [:]

          /// Optional. Sample request for deployed endpoint.
          public var sampleRequest: Swift.String = Swift.String()

          /// Initialize a new instance of `DeployMetadata`.
          public init() {}

          /// Use `config` to return a new instance of this object, with some fields updated.
          ///
          /// Commonly used to initialize the value, for example:
          ///
          /// ```
          /// let value = DeployMetadata().with { $0.labels = ... }
          /// ```
          public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
            var copy = self
            try config(&copy)
            return copy
          }

          public static var _anyTypeUrl: Swift.String {
            return
              "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.CallToAction.Deploy.DeployMetadata"
          }
          public init(fromAny any: GoogleCloudWkt.`Any`) throws {
            self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
          }
          public func _pack() throws -> GoogleCloudWkt.Struct {
            return try GoogleCloudWkt._slowAnySerialize(message: self)
          }
        }

        /// The prediction (for example, the machine) resources that the
        /// DeployedModel uses.
        public enum OneOf_PredictionResources: Codable, Equatable, Sendable {
          /// A description of resources that are dedicated to the DeployedModel,
          /// and that need a higher degree of manual configuration.
          indirect case dedicatedResources(DedicatedResources?)
          /// A description of resources that to large degree are decided by Vertex
          /// AI, and require only a modest additional configuration.
          indirect case automaticResources(AutomaticResources?)
          /// The resource name of the shared DeploymentResourcePool to deploy on.
          /// Format:
          /// `projects/{project}/locations/{location}/deploymentResourcePools/{deployment_resource_pool}`
          case sharedResources(Swift.String)
        }

        public static var _anyTypeUrl: Swift.String {
          return "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.CallToAction.Deploy"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// Configurations for PublisherModel GKE deployment
      public struct DeployGke: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Optional. GKE deployment configuration in yaml format.
        public var gkeYamlConfigs: [Swift.String] = []

        /// Initialize a new instance of `DeployGke`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = DeployGke().with { $0.gkeYamlConfigs = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.CallToAction.DeployGke"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel.CallToAction"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// An enum representing the open source category of a PublisherModel.
    public enum OpenSourceCategory: Codable, Equatable, Sendable {
      /// The open source category is unspecified, which should not be used.
      case unspecified
      /// Used to indicate the PublisherModel is not open sourced.
      case proprietary
      /// Used to indicate the PublisherModel is a Google-owned open source model
      /// w/ Google checkpoint.
      case googleOwnedOssWithGoogleCheckpoint
      /// Used to indicate the PublisherModel is a 3p-owned open source model w/
      /// Google checkpoint.
      case thirdPartyOwnedOssWithGoogleCheckpoint
      /// Used to indicate the PublisherModel is a Google-owned pure open source
      /// model.
      case googleOwnedOss
      /// Used to indicate the PublisherModel is a 3p-owned pure open source model.
      case thirdPartyOwnedOss
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .proprietary: return 1
        case .googleOwnedOssWithGoogleCheckpoint: return 2
        case .thirdPartyOwnedOssWithGoogleCheckpoint: return 3
        case .googleOwnedOss: return 4
        case .thirdPartyOwnedOss: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "OPEN_SOURCE_CATEGORY_UNSPECIFIED"
        case .proprietary: return "PROPRIETARY"
        case .googleOwnedOssWithGoogleCheckpoint: return "GOOGLE_OWNED_OSS_WITH_GOOGLE_CHECKPOINT"
        case .thirdPartyOwnedOssWithGoogleCheckpoint:
          return "THIRD_PARTY_OWNED_OSS_WITH_GOOGLE_CHECKPOINT"
        case .googleOwnedOss: return "GOOGLE_OWNED_OSS"
        case .thirdPartyOwnedOss: return "THIRD_PARTY_OWNED_OSS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OpenSourceCategory/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "OPEN_SOURCE_CATEGORY_UNSPECIFIED": self = .unspecified
        case "PROPRIETARY": self = .proprietary
        case "GOOGLE_OWNED_OSS_WITH_GOOGLE_CHECKPOINT": self = .googleOwnedOssWithGoogleCheckpoint
        case "THIRD_PARTY_OWNED_OSS_WITH_GOOGLE_CHECKPOINT":
          self = .thirdPartyOwnedOssWithGoogleCheckpoint
        case "GOOGLE_OWNED_OSS": self = .googleOwnedOss
        case "THIRD_PARTY_OWNED_OSS": self = .thirdPartyOwnedOss
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OpenSourceCategory/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .proprietary
        case 2: self = .googleOwnedOssWithGoogleCheckpoint
        case 3: self = .thirdPartyOwnedOssWithGoogleCheckpoint
        case 4: self = .googleOwnedOss
        case 5: self = .thirdPartyOwnedOss
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .proprietary: return try container.encode(1)
        case .googleOwnedOssWithGoogleCheckpoint: return try container.encode(2)
        case .thirdPartyOwnedOssWithGoogleCheckpoint: return try container.encode(3)
        case .googleOwnedOss: return try container.encode(4)
        case .thirdPartyOwnedOss: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// An enum representing the launch stage of a PublisherModel.
    public enum LaunchStage: Codable, Equatable, Sendable {
      /// The model launch stage is unspecified.
      case unspecified
      /// Used to indicate the PublisherModel is at Experimental launch stage,
      /// available to a small set of customers.
      case experimental
      /// Used to indicate the PublisherModel is at Private Preview launch stage,
      /// only available to a small set of customers, although a larger set of
      /// customers than an Experimental launch. Previews are the first launch
      /// stage used to get feedback from customers.
      case privatePreview
      /// Used to indicate the PublisherModel is at Public Preview launch stage,
      /// available to all customers, although not supported for production
      /// workloads.
      case publicPreview
      /// Used to indicate the PublisherModel is at GA launch stage, available to
      /// all customers and ready for production workload.
      case ga
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .experimental: return 1
        case .privatePreview: return 2
        case .publicPreview: return 3
        case .ga: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "LAUNCH_STAGE_UNSPECIFIED"
        case .experimental: return "EXPERIMENTAL"
        case .privatePreview: return "PRIVATE_PREVIEW"
        case .publicPreview: return "PUBLIC_PREVIEW"
        case .ga: return "GA"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LaunchStage/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "LAUNCH_STAGE_UNSPECIFIED": self = .unspecified
        case "EXPERIMENTAL": self = .experimental
        case "PRIVATE_PREVIEW": self = .privatePreview
        case "PUBLIC_PREVIEW": self = .publicPreview
        case "GA": self = .ga
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LaunchStage/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .experimental
        case 2: self = .privatePreview
        case 3: self = .publicPreview
        case 4: self = .ga
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .experimental: return try container.encode(1)
        case .privatePreview: return try container.encode(2)
        case .publicPreview: return try container.encode(3)
        case .ga: return try container.encode(4)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// An enum representing the state of the PublicModelVersion.
    public enum VersionState: Codable, Equatable, Sendable {
      /// The version state is unspecified.
      case unspecified
      /// Used to indicate the version is stable.
      case stable
      /// Used to indicate the version is unstable.
      case unstable
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .stable: return 1
        case .unstable: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "VERSION_STATE_UNSPECIFIED"
        case .stable: return "VERSION_STATE_STABLE"
        case .unstable: return "VERSION_STATE_UNSTABLE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VersionState/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "VERSION_STATE_UNSPECIFIED": self = .unspecified
        case "VERSION_STATE_STABLE": self = .stable
        case "VERSION_STATE_UNSTABLE": self = .unstable
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VersionState/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .stable
        case 2: self = .unstable
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .stable: return try container.encode(1)
        case .unstable: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.PublisherModel"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
