// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if VertexRagDataService
  import Foundation
  import GoogleCloudWkt

  /// Specifies the parsing config for RagFiles.
  public struct RagFileParsingConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The parser to use for RagFiles.
    public var parser: OneOf_Parser? = nil

    /// Initialize a new instance of `RagFileParsingConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RagFileParsingConfig().with { $0.layoutParser = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case layoutParser = "layoutParser"
      case llmParser = "llmParser"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var parser: OneOf_Parser? = nil
      let parserCheckAndSet = {
        if parser != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'parser'"))
        }
        parser = $0
      }
      if let layoutParser = try container.decodeIfPresent(
        RagFileParsingConfig.LayoutParser?.self, forKey: .layoutParser)
      {
        try parserCheckAndSet(.layoutParser(layoutParser))
      }
      if let llmParser = try container.decodeIfPresent(
        RagFileParsingConfig.LlmParser?.self, forKey: .llmParser)
      {
        try parserCheckAndSet(.llmParser(llmParser))
      }
      self.parser = parser
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.parser {
        switch choice {
        case .layoutParser(let value):
          try container.encode(value, forKey: .layoutParser)
        case .llmParser(let value):
          try container.encode(value, forKey: .llmParser)
        }
      }
    }

    /// Document AI Layout Parser config.
    public struct LayoutParser: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The full resource name of a Document AI processor or processor version.
      /// The processor must have type `LAYOUT_PARSER_PROCESSOR`. If specified, the
      /// `additional_config.parse_as_scanned_pdf` field must be false.
      /// Format:
      /// * `projects/{project_id}/locations/{location}/processors/{processor_id}`
      /// * `projects/{project_id}/locations/{location}/processors/{processor_id}/processorVersions/{processor_version_id}`
      public var processorName: Swift.String = Swift.String()

      /// The maximum number of requests the job is allowed to make to the Document
      /// AI processor per minute. Consult
      /// https://cloud.google.com/document-ai/quotas and the Quota page for your
      /// project to set an appropriate value here. If unspecified, a default value
      /// of 120 QPM would be used.
      public var maxParsingRequestsPerMin: Swift.Int32 = Swift.Int32()

      /// Initialize a new instance of `LayoutParser`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = LayoutParser().with { $0.processorName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.RagFileParsingConfig.LayoutParser"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Specifies the advanced parsing for RagFiles.
    public struct LlmParser: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The name of a LLM model used for parsing.
      /// Format:
      /// * `projects/{project_id}/locations/{location}/publishers/{publisher}/models/{model}`
      public var modelName: Swift.String = Swift.String()

      /// The maximum number of requests the job is allowed to make to the
      /// LLM model per minute. Consult
      /// https://cloud.google.com/vertex-ai/generative-ai/docs/quotas
      /// and your document size to set an appropriate value here. If unspecified,
      /// a default value of 5000 QPM would be used.
      public var maxParsingRequestsPerMin: Swift.Int32 = Swift.Int32()

      /// The prompt to use for parsing. If not specified, a default prompt will
      /// be used.
      public var customParsingPrompt: Swift.String = Swift.String()

      /// Initialize a new instance of `LlmParser`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = LlmParser().with { $0.modelName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.aiplatform.v1.RagFileParsingConfig.LlmParser"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// The parser to use for RagFiles.
    public enum OneOf_Parser: Codable, Equatable, Sendable {
      /// The Layout Parser to use for RagFiles.
      indirect case layoutParser(RagFileParsingConfig.LayoutParser?)
      /// The LLM Parser to use for RagFiles.
      indirect case llmParser(RagFileParsingConfig.LlmParser?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.RagFileParsingConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
