// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PersistentResourceService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Configuration information for the Ray cluster.
  /// For experimental launch, Ray cluster creation and Persistent
  /// cluster creation are 1:1 mapping: We will provision all the nodes within the
  /// Persistent cluster as Ray nodes.
  public struct RaySpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Default image for user to choose a preferred ML framework
    /// (for example, TensorFlow or Pytorch) by choosing from [Vertex prebuilt
    /// images](https://cloud.google.com/vertex-ai/docs/training/pre-built-containers).
    /// Either this or the resource_pool_images is required. Use this field if
    /// you need all the resource pools to have the same Ray image. Otherwise, use
    /// the {@code resource_pool_images} field.
    public var imageUri: Swift.String = Swift.String()

    /// Optional. Required if image_uri isn't set. A map of resource_pool_id to
    /// prebuild Ray image if user need to use different images for different
    /// head/worker pools. This map needs to cover all the resource pool ids.
    /// Example:
    /// {
    ///   "ray_head_node_pool": "head image"
    ///   "ray_worker_node_pool1": "worker image"
    ///   "ray_worker_node_pool2": "another worker image"
    /// }
    public var resourcePoolImages: [Swift.String: Swift.String] = [:]

    /// Optional. This will be used to indicate which resource pool will serve as
    /// the Ray head node(the first node within that pool). Will use the machine
    /// from the first workerpool as the head node by default if this field isn't
    /// set.
    public var headNodeResourcePoolId: Swift.String = Swift.String()

    /// Optional. Ray metrics configurations.
    public var rayMetricSpec: RayMetricSpec? = nil

    /// Optional. OSS Ray logging configurations.
    public var rayLogsSpec: RayLogsSpec? = nil

    /// Initialize a new instance of `RaySpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RaySpec().with { $0.imageUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.RaySpec"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
