// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GenAiTuningService || LlmUtilityService || PredictionService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Configuration for speech generation.
  public struct SpeechConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The configuration for the voice to use.
    public var voiceConfig: VoiceConfig? = nil

    /// Optional. The language code (ISO 639-1) for the speech synthesis.
    public var languageCode: Swift.String = Swift.String()

    /// The configuration for a multi-speaker text-to-speech request.
    /// This field is mutually exclusive with `voice_config`.
    public var multiSpeakerVoiceConfig: MultiSpeakerVoiceConfig? = nil

    /// Initialize a new instance of `SpeechConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SpeechConfig().with { $0.voiceConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.SpeechConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
