// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GenAiTuningService
  import Foundation
  import GoogleCloudWkt

  /// Hyperparameters for SFT.
  public struct SupervisedHyperParameters: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Number of complete passes the model makes over the entire
    /// training dataset during training.
    public var epochCount: Swift.Int64 = Swift.Int64()

    /// Optional. Multiplier for adjusting the default learning rate.
    public var learningRateMultiplier: Swift.Double = Swift.Double()

    /// Optional. Adapter size for tuning.
    public var adapterSize: SupervisedHyperParameters.AdapterSize =
      SupervisedHyperParameters.AdapterSize()

    /// Initialize a new instance of `SupervisedHyperParameters`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SupervisedHyperParameters().with { $0.epochCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Supported adapter sizes for tuning.
    public enum AdapterSize: Codable, Equatable, Sendable {
      /// Adapter size is unspecified.
      case unspecified
      /// Adapter size 1.
      case one
      /// Adapter size 4.
      case four
      /// Adapter size 8.
      case eight
      /// Adapter size 16.
      case sixteen
      /// Adapter size 32.
      case thirtyTwo
      /// Adapter size 2.
      case two
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .one: return 1
        case .four: return 2
        case .eight: return 3
        case .sixteen: return 4
        case .thirtyTwo: return 5
        case .two: return 6
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ADAPTER_SIZE_UNSPECIFIED"
        case .one: return "ADAPTER_SIZE_ONE"
        case .four: return "ADAPTER_SIZE_FOUR"
        case .eight: return "ADAPTER_SIZE_EIGHT"
        case .sixteen: return "ADAPTER_SIZE_SIXTEEN"
        case .thirtyTwo: return "ADAPTER_SIZE_THIRTY_TWO"
        case .two: return "ADAPTER_SIZE_TWO"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AdapterSize/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ADAPTER_SIZE_UNSPECIFIED": self = .unspecified
        case "ADAPTER_SIZE_ONE": self = .one
        case "ADAPTER_SIZE_TWO": self = .two
        case "ADAPTER_SIZE_FOUR": self = .four
        case "ADAPTER_SIZE_EIGHT": self = .eight
        case "ADAPTER_SIZE_SIXTEEN": self = .sixteen
        case "ADAPTER_SIZE_THIRTY_TWO": self = .thirtyTwo
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AdapterSize/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .one
        case 2: self = .four
        case 3: self = .eight
        case 4: self = .sixteen
        case 5: self = .thirtyTwo
        case 6: self = .two
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .one: return try container.encode(1)
        case .four: return try container.encode(2)
        case .eight: return try container.encode(3)
        case .sixteen: return try container.encode(4)
        case .thirtyTwo: return try container.encode(5)
        case .two: return try container.encode(6)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.SupervisedHyperParameters"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
