// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TensorboardService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleIAMV1
  import GoogleLongRunning
  import GoogleRpc
  import GoogleWKT
  @_spi(GoogleCloudInternal) import GoogleGax

  extension Clients {
    final class TensorboardServiceRetry: TensorboardServiceStub {
      let inner: any TensorboardServiceStub
      let options: GoogleGax.ClientOptions

      public init(_ inner: any TensorboardServiceStub, options: GoogleGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func createTensorboard(
        request: CreateTensorboardRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: CreateTensorboardRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.createTensorboard(request: r, options: o)
          })
      }

      public func getTensorboard(
        request: GetTensorboardRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.Tensorboard {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GetTensorboardRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.Tensorboard
            in
            return try await self.inner.getTensorboard(request: r, options: o)
          })
      }

      public func updateTensorboard(
        request: UpdateTensorboardRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: UpdateTensorboardRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.updateTensorboard(request: r, options: o)
          })
      }

      public func listTensorboards(
        request: ListTensorboardsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListTensorboardsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ListTensorboardsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ListTensorboardsResponse
            in
            return try await self.inner.listTensorboards(request: r, options: o)
          })
      }

      public func deleteTensorboard(
        request: DeleteTensorboardRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DeleteTensorboardRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.deleteTensorboard(request: r, options: o)
          })
      }

      public func readTensorboardUsage(
        request: ReadTensorboardUsageRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReadTensorboardUsageResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ReadTensorboardUsageRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ReadTensorboardUsageResponse
            in
            return try await self.inner.readTensorboardUsage(request: r, options: o)
          })
      }

      public func readTensorboardSize(
        request: ReadTensorboardSizeRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReadTensorboardSizeResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ReadTensorboardSizeRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ReadTensorboardSizeResponse
            in
            return try await self.inner.readTensorboardSize(request: r, options: o)
          })
      }

      public func createTensorboardExperiment(
        request: CreateTensorboardExperimentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardExperiment {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: CreateTensorboardExperimentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardExperiment
            in
            return try await self.inner.createTensorboardExperiment(request: r, options: o)
          })
      }

      public func getTensorboardExperiment(
        request: GetTensorboardExperimentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardExperiment {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GetTensorboardExperimentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardExperiment
            in
            return try await self.inner.getTensorboardExperiment(request: r, options: o)
          })
      }

      public func updateTensorboardExperiment(
        request: UpdateTensorboardExperimentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardExperiment {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: UpdateTensorboardExperimentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardExperiment
            in
            return try await self.inner.updateTensorboardExperiment(request: r, options: o)
          })
      }

      public func listTensorboardExperiments(
        request: ListTensorboardExperimentsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListTensorboardExperimentsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ListTensorboardExperimentsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ListTensorboardExperimentsResponse
            in
            return try await self.inner.listTensorboardExperiments(request: r, options: o)
          })
      }

      public func deleteTensorboardExperiment(
        request: DeleteTensorboardExperimentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DeleteTensorboardExperimentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.deleteTensorboardExperiment(request: r, options: o)
          })
      }

      public func createTensorboardRun(
        request: CreateTensorboardRunRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardRun {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: CreateTensorboardRunRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardRun
            in
            return try await self.inner.createTensorboardRun(request: r, options: o)
          })
      }

      public func batchCreateTensorboardRuns(
        request: BatchCreateTensorboardRunsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.BatchCreateTensorboardRunsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: BatchCreateTensorboardRunsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.BatchCreateTensorboardRunsResponse
            in
            return try await self.inner.batchCreateTensorboardRuns(request: r, options: o)
          })
      }

      public func getTensorboardRun(
        request: GetTensorboardRunRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardRun {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GetTensorboardRunRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardRun
            in
            return try await self.inner.getTensorboardRun(request: r, options: o)
          })
      }

      public func updateTensorboardRun(
        request: UpdateTensorboardRunRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardRun {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: UpdateTensorboardRunRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardRun
            in
            return try await self.inner.updateTensorboardRun(request: r, options: o)
          })
      }

      public func listTensorboardRuns(
        request: ListTensorboardRunsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListTensorboardRunsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ListTensorboardRunsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ListTensorboardRunsResponse
            in
            return try await self.inner.listTensorboardRuns(request: r, options: o)
          })
      }

      public func deleteTensorboardRun(
        request: DeleteTensorboardRunRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DeleteTensorboardRunRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.deleteTensorboardRun(request: r, options: o)
          })
      }

      public func batchCreateTensorboardTimeSeries(
        request: BatchCreateTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.BatchCreateTensorboardTimeSeriesResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: BatchCreateTensorboardTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.BatchCreateTensorboardTimeSeriesResponse
            in
            return try await self.inner.batchCreateTensorboardTimeSeries(request: r, options: o)
          })
      }

      public func createTensorboardTimeSeries(
        request: CreateTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardTimeSeries {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: CreateTensorboardTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardTimeSeries
            in
            return try await self.inner.createTensorboardTimeSeries(request: r, options: o)
          })
      }

      public func getTensorboardTimeSeries(
        request: GetTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardTimeSeries {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GetTensorboardTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardTimeSeries
            in
            return try await self.inner.getTensorboardTimeSeries(request: r, options: o)
          })
      }

      public func updateTensorboardTimeSeries(
        request: UpdateTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardTimeSeries {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: UpdateTensorboardTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.TensorboardTimeSeries
            in
            return try await self.inner.updateTensorboardTimeSeries(request: r, options: o)
          })
      }

      public func listTensorboardTimeSeries(
        request: ListTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListTensorboardTimeSeriesResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ListTensorboardTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ListTensorboardTimeSeriesResponse
            in
            return try await self.inner.listTensorboardTimeSeries(request: r, options: o)
          })
      }

      public func deleteTensorboardTimeSeries(
        request: DeleteTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DeleteTensorboardTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.deleteTensorboardTimeSeries(request: r, options: o)
          })
      }

      public func batchReadTensorboardTimeSeriesData(
        request: BatchReadTensorboardTimeSeriesDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.BatchReadTensorboardTimeSeriesDataResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: BatchReadTensorboardTimeSeriesDataRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.BatchReadTensorboardTimeSeriesDataResponse
            in
            return try await self.inner.batchReadTensorboardTimeSeriesData(request: r, options: o)
          })
      }

      public func readTensorboardTimeSeriesData(
        request: ReadTensorboardTimeSeriesDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReadTensorboardTimeSeriesDataResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ReadTensorboardTimeSeriesDataRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ReadTensorboardTimeSeriesDataResponse
            in
            return try await self.inner.readTensorboardTimeSeriesData(request: r, options: o)
          })
      }

      public func readTensorboardBlobData(
        request: ReadTensorboardBlobDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReadTensorboardBlobDataResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ReadTensorboardBlobDataRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ReadTensorboardBlobDataResponse
            in
            return try await self.inner.readTensorboardBlobData(request: r, options: o)
          })
      }

      public func writeTensorboardExperimentData(
        request: WriteTensorboardExperimentDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.WriteTensorboardExperimentDataResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: WriteTensorboardExperimentDataRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.WriteTensorboardExperimentDataResponse
            in
            return try await self.inner.writeTensorboardExperimentData(request: r, options: o)
          })
      }

      public func writeTensorboardRunData(
        request: WriteTensorboardRunDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.WriteTensorboardRunDataResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: WriteTensorboardRunDataRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.WriteTensorboardRunDataResponse
            in
            return try await self.inner.writeTensorboardRunData(request: r, options: o)
          })
      }

      public func exportTensorboardTimeSeriesData(
        request: ExportTensorboardTimeSeriesDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ExportTensorboardTimeSeriesDataResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: ExportTensorboardTimeSeriesDataRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudAIPlatformV1.ExportTensorboardTimeSeriesDataResponse
            in
            return try await self.inner.exportTensorboardTimeSeriesData(request: r, options: o)
          })
      }

      public func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudLocation.ListLocationsResponse
            in
            return try await self.inner.listLocations(request: r, options: o)
          })
      }

      public func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudLocation.Location
            in
            return try await self.inner.getLocation(request: r, options: o)
          })
      }

      public func setIamPolicy(
        request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleIAMV1.Policy
            in
            return try await self.inner.setIamPolicy(request: r, options: o)
          })
      }

      public func getIamPolicy(
        request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleIAMV1.Policy
            in
            return try await self.inner.getIamPolicy(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleIAMV1.TestIamPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func deleteOperation(
        request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> Void in
            return try await self.inner.deleteOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }

      public func waitOperation(
        request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleLongRunning.WaitOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.waitOperation(request: r, options: o)
          })
      }
    }
  }
#endif
