// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TensorboardService
  import Foundation
  import GoogleCloudLocation
  import GoogleIAMV1
  import GoogleLongRunning
  import GoogleRpc
  import GoogleWKT
  import GoogleGax

  extension Clients {
    protocol TensorboardServiceStub: Sendable {
      func createTensorboard(
        request: CreateTensorboardRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func getTensorboard(
        request: GetTensorboardRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.Tensorboard

      func updateTensorboard(
        request: UpdateTensorboardRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func listTensorboards(
        request: ListTensorboardsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListTensorboardsResponse

      func deleteTensorboard(
        request: DeleteTensorboardRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func readTensorboardUsage(
        request: ReadTensorboardUsageRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReadTensorboardUsageResponse

      func readTensorboardSize(
        request: ReadTensorboardSizeRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReadTensorboardSizeResponse

      func createTensorboardExperiment(
        request: CreateTensorboardExperimentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardExperiment

      func getTensorboardExperiment(
        request: GetTensorboardExperimentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardExperiment

      func updateTensorboardExperiment(
        request: UpdateTensorboardExperimentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardExperiment

      func listTensorboardExperiments(
        request: ListTensorboardExperimentsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListTensorboardExperimentsResponse

      func deleteTensorboardExperiment(
        request: DeleteTensorboardExperimentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func createTensorboardRun(
        request: CreateTensorboardRunRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardRun

      func batchCreateTensorboardRuns(
        request: BatchCreateTensorboardRunsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.BatchCreateTensorboardRunsResponse

      func getTensorboardRun(
        request: GetTensorboardRunRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardRun

      func updateTensorboardRun(
        request: UpdateTensorboardRunRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardRun

      func listTensorboardRuns(
        request: ListTensorboardRunsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListTensorboardRunsResponse

      func deleteTensorboardRun(
        request: DeleteTensorboardRunRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func batchCreateTensorboardTimeSeries(
        request: BatchCreateTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.BatchCreateTensorboardTimeSeriesResponse

      func createTensorboardTimeSeries(
        request: CreateTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardTimeSeries

      func getTensorboardTimeSeries(
        request: GetTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardTimeSeries

      func updateTensorboardTimeSeries(
        request: UpdateTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.TensorboardTimeSeries

      func listTensorboardTimeSeries(
        request: ListTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ListTensorboardTimeSeriesResponse

      func deleteTensorboardTimeSeries(
        request: DeleteTensorboardTimeSeriesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func batchReadTensorboardTimeSeriesData(
        request: BatchReadTensorboardTimeSeriesDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.BatchReadTensorboardTimeSeriesDataResponse

      func readTensorboardTimeSeriesData(
        request: ReadTensorboardTimeSeriesDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReadTensorboardTimeSeriesDataResponse

      func readTensorboardBlobData(
        request: ReadTensorboardBlobDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ReadTensorboardBlobDataResponse

      func writeTensorboardExperimentData(
        request: WriteTensorboardExperimentDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.WriteTensorboardExperimentDataResponse

      func writeTensorboardRunData(
        request: WriteTensorboardRunDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.WriteTensorboardRunDataResponse

      func exportTensorboardTimeSeriesData(
        request: ExportTensorboardTimeSeriesDataRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudAIPlatformV1.ExportTensorboardTimeSeriesDataResponse

      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      func setIamPolicy(
        request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      func getIamPolicy(
        request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.Policy

      func testIamPermissions(
        request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func deleteOperation(
        request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws

      func waitOperation(
        request: GoogleLongRunning.WaitOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation
    }
  }
#endif
