// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TensorboardService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Tensorboard is a physical database that stores users' training metrics.
  /// A default Tensorboard is provided in each region of a Google Cloud project.
  /// If needed users can also create extra Tensorboards in their projects.
  public struct Tensorboard: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Name of the Tensorboard.
    /// Format:
    /// `projects/{project}/locations/{location}/tensorboards/{tensorboard}`
    public var name: Swift.String = Swift.String()

    /// Required. User provided name of this Tensorboard.
    public var displayName: Swift.String = Swift.String()

    /// Description of this Tensorboard.
    public var description: Swift.String = Swift.String()

    /// Customer-managed encryption key spec for a Tensorboard. If set, this
    /// Tensorboard and all sub-resources of this Tensorboard will be secured by
    /// this key.
    public var encryptionSpec: EncryptionSpec? = nil

    /// Output only. Consumer project Cloud Storage path prefix used to store blob
    /// data, which can either be a bucket or directory. Does not end with a '/'.
    public var blobStoragePathPrefix: Swift.String = Swift.String()

    /// Output only. The number of Runs stored in this Tensorboard.
    public var runCount: Swift.Int32 = Swift.Int32()

    /// Output only. Timestamp when this Tensorboard was created.
    public var createTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. Timestamp when this Tensorboard was last updated.
    public var updateTime: GoogleCloudWkt.Timestamp? = nil

    /// The labels with user-defined metadata to organize your Tensorboards.
    ///
    /// Label keys and values can be no longer than 64 characters
    /// (Unicode codepoints), can only contain lowercase letters, numeric
    /// characters, underscores and dashes. International characters are allowed.
    /// No more than 64 user labels can be associated with one Tensorboard
    /// (System labels are excluded).
    ///
    /// See https://goo.gl/xmQnxf for more information and examples of labels.
    /// System reserved label keys are prefixed with "aiplatform.googleapis.com/"
    /// and are immutable.
    public var labels: [Swift.String: Swift.String] = [:]

    /// Used to perform a consistent read-modify-write updates. If not set, a blind
    /// "overwrite" update happens.
    public var etag: Swift.String = Swift.String()

    /// Used to indicate if the TensorBoard instance is the default one.
    /// Each project & region can have at most one default TensorBoard instance.
    /// Creation of a default TensorBoard instance and updating an existing
    /// TensorBoard instance to be default will mark all other TensorBoard
    /// instances (if any) as non default.
    public var isDefault: Swift.Bool = Swift.Bool()

    /// Output only. Reserved for future use.
    public var satisfiesPzs: Swift.Bool = Swift.Bool()

    /// Output only. Reserved for future use.
    public var satisfiesPzi: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `Tensorboard`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Tensorboard().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.Tensorboard"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
