// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if JobService
  import Foundation
  import GoogleCloudWkt

  /// Request message for
  /// [JobService.UpdateModelDeploymentMonitoringJob][google.cloud.aiplatform.v1.JobService.UpdateModelDeploymentMonitoringJob].
  ///
  /// [google.cloud.aiplatform.v1.JobService.UpdateModelDeploymentMonitoringJob]: <doc:JobService/updateModelDeploymentMonitoringJob(request:)>
  public struct UpdateModelDeploymentMonitoringJobRequest: Codable, Equatable, GoogleCloudWkt
      ._AnyPackable,
    Sendable
  {
    /// Required. The model monitoring configuration which replaces the resource on
    /// the server.
    public var modelDeploymentMonitoringJob: ModelDeploymentMonitoringJob? = nil

    /// Required. The update mask is used to specify the fields to be overwritten
    /// in the ModelDeploymentMonitoringJob resource by the update. The fields
    /// specified in the update_mask are relative to the resource, not the full
    /// request. A field will be overwritten if it is in the mask. If the user does
    /// not provide a mask then only the non-empty fields present in the request
    /// will be overwritten. Set the update_mask to `*` to override all fields. For
    /// the objective config, the user can either provide the update mask for
    /// model_deployment_monitoring_objective_configs or any combination of its
    /// nested fields, such as:
    /// model_deployment_monitoring_objective_configs.objective_config.training_dataset.
    ///
    /// Updatable fields:
    ///
    ///   * `display_name`
    ///   * `model_deployment_monitoring_schedule_config`
    ///   * `model_monitoring_alert_config`
    ///   * `logging_sampling_strategy`
    ///   * `labels`
    ///   * `log_ttl`
    ///   * `enable_monitoring_pipeline_logs`
    /// .  and
    ///   * `model_deployment_monitoring_objective_configs`
    /// .  or
    ///   * `model_deployment_monitoring_objective_configs.objective_config.training_dataset`
    ///   * `model_deployment_monitoring_objective_configs.objective_config.training_prediction_skew_detection_config`
    ///   * `model_deployment_monitoring_objective_configs.objective_config.prediction_drift_detection_config`
    public var updateMask: GoogleCloudWkt.FieldMask? = nil

    /// Initialize a new instance of `UpdateModelDeploymentMonitoringJobRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UpdateModelDeploymentMonitoringJobRequest().with { $0.modelDeploymentMonitoringJob = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.aiplatform.v1.UpdateModelDeploymentMonitoringJobRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
