// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if NotebookService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Metadata information for
  /// [NotebookService.UpgradeNotebookRuntime][google.cloud.aiplatform.v1.NotebookService.UpgradeNotebookRuntime].
  ///
  /// [google.cloud.aiplatform.v1.NotebookService.UpgradeNotebookRuntime]: <doc:NotebookServiceClient/upgradeNotebookRuntime(request:options:)>
  public struct UpgradeNotebookRuntimeOperationMetadata: Codable, Equatable, GoogleCloudWkt
      ._AnyPackable,
    Sendable
  {
    /// The operation generic information.
    public var genericMetadata: GenericOperationMetadata? = nil

    /// A human-readable message that shows the intermediate progress details of
    /// NotebookRuntime.
    public var progressMessage: Swift.String = Swift.String()

    /// Initialize a new instance of `UpgradeNotebookRuntimeOperationMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UpgradeNotebookRuntimeOperationMetadata().with { $0.genericMetadata = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.aiplatform.v1.UpgradeNotebookRuntimeOperationMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
