// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if PredictionService
  import Foundation
  import GoogleCloudWkt

  /// Usage metadata about the content generation request and response.
  /// This message provides a detailed breakdown of token usage and other
  /// relevant metrics.
  public struct UsageMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The total number of tokens in the prompt. This includes any text, images,
    /// or other media provided in the request. When `cached_content` is set,
    /// this also includes the number of tokens in the cached content.
    public var promptTokenCount: Swift.Int32 = Swift.Int32()

    /// The total number of tokens in the generated candidates.
    public var candidatesTokenCount: Swift.Int32 = Swift.Int32()

    /// The total number of tokens for the entire request. This is the sum of
    /// `prompt_token_count`, `candidates_token_count`,
    /// `tool_use_prompt_token_count`, and `thoughts_token_count`.
    public var totalTokenCount: Swift.Int32 = Swift.Int32()

    /// Output only. The number of tokens in the results from tool executions,
    /// which are provided back to the model as input, if applicable.
    public var toolUsePromptTokenCount: Swift.Int32 = Swift.Int32()

    /// Output only. The number of tokens that were part of the model's generated
    /// "thoughts" output, if applicable.
    public var thoughtsTokenCount: Swift.Int32 = Swift.Int32()

    /// Output only. The number of tokens in the cached content that was used for
    /// this request.
    public var cachedContentTokenCount: Swift.Int32 = Swift.Int32()

    /// Output only. A detailed breakdown of the token count for each modality in
    /// the prompt.
    public var promptTokensDetails: [ModalityTokenCount] = []

    /// Output only. A detailed breakdown of the token count for each modality in
    /// the cached content.
    public var cacheTokensDetails: [ModalityTokenCount] = []

    /// Output only. A detailed breakdown of the token count for each modality in
    /// the generated candidates.
    public var candidatesTokensDetails: [ModalityTokenCount] = []

    /// Output only. A detailed breakdown by modality of the token counts from the
    /// results of tool executions, which are provided back to the model as input.
    public var toolUsePromptTokensDetails: [ModalityTokenCount] = []

    /// Output only. The traffic type for this request.
    public var trafficType: UsageMetadata.TrafficType = UsageMetadata.TrafficType()

    /// Initialize a new instance of `UsageMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UsageMetadata().with { $0.promptTokenCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The type of traffic that this request was processed with, indicating which
    /// quota gets consumed.
    public enum TrafficType: Codable, Equatable, Sendable {
      /// Unspecified request traffic type.
      case unspecified
      /// Type for Pay-As-You-Go traffic.
      case onDemand
      /// Type for Provisioned Throughput traffic.
      case provisionedThroughput
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .onDemand: return 1
        case .provisionedThroughput: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TRAFFIC_TYPE_UNSPECIFIED"
        case .onDemand: return "ON_DEMAND"
        case .provisionedThroughput: return "PROVISIONED_THROUGHPUT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TRAFFIC_TYPE_UNSPECIFIED": self = .unspecified
        case "ON_DEMAND": self = .onDemand
        case "PROVISIONED_THROUGHPUT": self = .provisionedThroughput
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .onDemand
        case 2: self = .provisionedThroughput
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .onDemand: return try container.encode(1)
        case .provisionedThroughput: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.UsageMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
