// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GenAiTuningService || LlmUtilityService || PredictionService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Configuration for a voice.
  public struct VoiceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The configuration for the speaker to use.
    public var voiceConfig: OneOf_VoiceConfig? = nil

    /// Initialize a new instance of `VoiceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VoiceConfig().with { $0.prebuiltVoiceConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case prebuiltVoiceConfig = "prebuiltVoiceConfig"
      case replicatedVoiceConfig = "replicatedVoiceConfig"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var voiceConfig: OneOf_VoiceConfig? = nil
      let voiceConfigCheckAndSet = {
        if voiceConfig != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'voiceConfig'"))
        }
        voiceConfig = $0
      }
      if let prebuiltVoiceConfig = try container.decodeIfPresent(
        PrebuiltVoiceConfig?.self, forKey: .prebuiltVoiceConfig)
      {
        try voiceConfigCheckAndSet(.prebuiltVoiceConfig(prebuiltVoiceConfig))
      }
      if let replicatedVoiceConfig = try container.decodeIfPresent(
        ReplicatedVoiceConfig?.self, forKey: .replicatedVoiceConfig)
      {
        try voiceConfigCheckAndSet(.replicatedVoiceConfig(replicatedVoiceConfig))
      }
      self.voiceConfig = voiceConfig
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.voiceConfig {
        switch choice {
        case .prebuiltVoiceConfig(let value):
          try container.encode(value, forKey: .prebuiltVoiceConfig)
        case .replicatedVoiceConfig(let value):
          try container.encode(value, forKey: .replicatedVoiceConfig)
        }
      }
    }

    /// The configuration for the speaker to use.
    public enum OneOf_VoiceConfig: Codable, Equatable, Sendable {
      /// The configuration for a prebuilt voice.
      indirect case prebuiltVoiceConfig(PrebuiltVoiceConfig?)
      /// Optional. The configuration for a replicated voice. This enables users to
      /// replicate a voice from an audio sample.
      indirect case replicatedVoiceConfig(ReplicatedVoiceConfig?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.VoiceConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
