// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if JobService
  import Foundation
  import GoogleCloudWkt

  /// Represents the spec of a worker pool in a job.
  public struct WorkerPoolSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Immutable. The specification of a single machine.
    public var machineSpec: MachineSpec? = nil

    /// Optional. The number of worker replicas to use for this worker pool.
    public var replicaCount: Swift.Int64 = Swift.Int64()

    /// Optional. List of NFS mount spec.
    public var nfsMounts: [NfsMount] = []

    /// Optional. List of Lustre mounts.
    public var lustreMounts: [LustreMount] = []

    /// Disk spec.
    public var diskSpec: DiskSpec? = nil

    /// The custom task to be executed in this worker pool.
    public var task: OneOf_Task? = nil

    /// Initialize a new instance of `WorkerPoolSpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WorkerPoolSpec().with { $0.containerSpec = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case containerSpec = "containerSpec"
      case pythonPackageSpec = "pythonPackageSpec"
      case machineSpec = "machineSpec"
      case replicaCount = "replicaCount"
      case nfsMounts = "nfsMounts"
      case lustreMounts = "lustreMounts"
      case diskSpec = "diskSpec"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.machineSpec = try container.decodeIfPresent(MachineSpec.self, forKey: .machineSpec)
      self.replicaCount = try container.decode(Swift.Int64.self, forKey: .replicaCount)
      self.nfsMounts = try container.decode([NfsMount].self, forKey: .nfsMounts)
      self.lustreMounts = try container.decode([LustreMount].self, forKey: .lustreMounts)
      self.diskSpec = try container.decodeIfPresent(DiskSpec.self, forKey: .diskSpec)

      var task: OneOf_Task? = nil
      let taskCheckAndSet = {
        if task != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'task'"))
        }
        task = $0
      }
      if let containerSpec = try container.decodeIfPresent(
        ContainerSpec?.self, forKey: .containerSpec)
      {
        try taskCheckAndSet(.containerSpec(containerSpec))
      }
      if let pythonPackageSpec = try container.decodeIfPresent(
        PythonPackageSpec?.self, forKey: .pythonPackageSpec)
      {
        try taskCheckAndSet(.pythonPackageSpec(pythonPackageSpec))
      }
      self.task = task
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.machineSpec, forKey: .machineSpec)
      try container.encode(self.replicaCount, forKey: .replicaCount)
      try container.encode(self.nfsMounts, forKey: .nfsMounts)
      try container.encode(self.lustreMounts, forKey: .lustreMounts)
      try container.encode(self.diskSpec, forKey: .diskSpec)

      if let choice = self.task {
        switch choice {
        case .containerSpec(let value):
          try container.encode(value, forKey: .containerSpec)
        case .pythonPackageSpec(let value):
          try container.encode(value, forKey: .pythonPackageSpec)
        }
      }
    }

    /// The custom task to be executed in this worker pool.
    public enum OneOf_Task: Codable, Equatable, Sendable {
      /// The custom container task.
      indirect case containerSpec(ContainerSpec?)
      /// The Python packaged task.
      indirect case pythonPackageSpec(PythonPackageSpec?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.WorkerPoolSpec"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
