// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TensorboardService
  import Foundation
  import GoogleCloudWkt

  /// Request message for
  /// [TensorboardService.WriteTensorboardExperimentData][google.cloud.aiplatform.v1.TensorboardService.WriteTensorboardExperimentData].
  ///
  /// [google.cloud.aiplatform.v1.TensorboardService.WriteTensorboardExperimentData]: <doc:TensorboardService/writeTensorboardExperimentData(request:)>
  public struct WriteTensorboardExperimentDataRequest: Codable, Equatable, GoogleCloudWkt
      ._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the TensorboardExperiment to write data to.
    /// Format:
    /// `projects/{project}/locations/{location}/tensorboards/{tensorboard}/experiments/{experiment}`
    public var tensorboardExperiment: Swift.String = Swift.String()

    /// Required. Requests containing per-run TensorboardTimeSeries data to write.
    public var writeRunDataRequests: [WriteTensorboardRunDataRequest] = []

    /// Initialize a new instance of `WriteTensorboardExperimentDataRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WriteTensorboardExperimentDataRequest().with { $0.tensorboardExperiment = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.aiplatform.v1.WriteTensorboardExperimentDataRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
